/**
 * JACLIBC SYSCALLS MATRIX  //  last updated: 2025-11-28 20:09:33 UTC
 */

/* check SYS_alarm */
#define __config_has_has_alarm 0
#define __darwin_arm64_has_alarm 0
#define __darwin_generic_has_alarm 0
#define __darwin_x64_has_alarm 0
#define __dragonfly_generic_has_alarm 0
#define __dragonfly_x64_has_alarm 0
#define __dragonfly_x86_has_alarm 0
#define __format_auxv_has_alarm 0
#define __format_elf_has_alarm 0
#define __format_em_has_alarm 0
#define __format_macho_has_alarm 0
#define __format_pe_has_alarm 0
#define __freebsd_generic_has_alarm 0
#define __freebsd_x64_has_alarm 0
#define __freebsd_x86_has_alarm 0
#define __linux_alpha_has_alarm 0
#define __linux_arc_has_alarm 0
#define __linux_arm32_has_alarm 0
#define __linux_arm64_has_alarm 0
#define __linux_csky_has_alarm 0
#define __linux_generic_has_alarm 0
#define __linux_hexagon_has_alarm 0
#define __linux_hppa_has_alarm 1
#define __linux_loongarch64_has_alarm 0
#define __linux_m68k_has_alarm 0
#define __linux_microblaze_has_alarm 0
#define __linux_mips32_has_alarm 1
#define __linux_mips64_has_alarm 1
#define __linux_nios2_has_alarm 0
#define __linux_or1k_has_alarm 0
#define __linux_powerpc32_has_alarm 1
#define __linux_powerpc64_has_alarm 1
#define __linux_riscv32_has_alarm 0
#define __linux_riscv64_has_alarm 0
#define __linux_s390x_has_alarm 1
#define __linux_sh4_has_alarm 1
#define __linux_sparc32_has_alarm 1
#define __linux_sparc64_has_alarm 1
#define __linux_x64_has_alarm 1
#define __linux_x86_has_alarm 1
#define __linux_xtensa_has_alarm 0
#define __netbsd_alpha_has_alarm 0
#define __netbsd_arm32_has_alarm 0
#define __netbsd_arm64_has_alarm 0
#define __netbsd_generic_has_alarm 0
#define __netbsd_hppa_has_alarm 0
#define __netbsd_ia64_has_alarm 0
#define __netbsd_powerpc32_has_alarm 0
#define __netbsd_powerpc64_has_alarm 0
#define __netbsd_riscv32_has_alarm 0
#define __netbsd_riscv64_has_alarm 0
#define __netbsd_sparc32_has_alarm 0
#define __netbsd_sparc64_has_alarm 0
#define __netbsd_vax_has_alarm 0
#define __netbsd_x64_has_alarm 0
#define __netbsd_x86_has_alarm 0
#define __openbsd_generic_has_alarm 0
#define __openbsd_x64_has_alarm 0
#define __openbsd_x86_has_alarm 0

/* check SYS_arch_prctl */
#define __config_has_has_arch_prctl 0
#define __darwin_arm64_has_arch_prctl 0
#define __darwin_generic_has_arch_prctl 0
#define __darwin_x64_has_arch_prctl 0
#define __dragonfly_generic_has_arch_prctl 0
#define __dragonfly_x64_has_arch_prctl 0
#define __dragonfly_x86_has_arch_prctl 0
#define __format_auxv_has_arch_prctl 0
#define __format_elf_has_arch_prctl 0
#define __format_em_has_arch_prctl 0
#define __format_macho_has_arch_prctl 0
#define __format_pe_has_arch_prctl 0
#define __freebsd_generic_has_arch_prctl 0
#define __freebsd_x64_has_arch_prctl 0
#define __freebsd_x86_has_arch_prctl 0
#define __linux_alpha_has_arch_prctl 0
#define __linux_arc_has_arch_prctl 0
#define __linux_arm32_has_arch_prctl 0
#define __linux_arm64_has_arch_prctl 0
#define __linux_csky_has_arch_prctl 0
#define __linux_generic_has_arch_prctl 0
#define __linux_hexagon_has_arch_prctl 0
#define __linux_hppa_has_arch_prctl 0
#define __linux_loongarch64_has_arch_prctl 0
#define __linux_m68k_has_arch_prctl 0
#define __linux_microblaze_has_arch_prctl 0
#define __linux_mips32_has_arch_prctl 0
#define __linux_mips64_has_arch_prctl 0
#define __linux_nios2_has_arch_prctl 0
#define __linux_or1k_has_arch_prctl 0
#define __linux_powerpc32_has_arch_prctl 0
#define __linux_powerpc64_has_arch_prctl 0
#define __linux_riscv32_has_arch_prctl 0
#define __linux_riscv64_has_arch_prctl 0
#define __linux_s390x_has_arch_prctl 0
#define __linux_sh4_has_arch_prctl 0
#define __linux_sparc32_has_arch_prctl 0
#define __linux_sparc64_has_arch_prctl 0
#define __linux_x64_has_arch_prctl 1
#define __linux_x86_has_arch_prctl 1
#define __linux_xtensa_has_arch_prctl 0
#define __netbsd_alpha_has_arch_prctl 0
#define __netbsd_arm32_has_arch_prctl 0
#define __netbsd_arm64_has_arch_prctl 0
#define __netbsd_generic_has_arch_prctl 0
#define __netbsd_hppa_has_arch_prctl 0
#define __netbsd_ia64_has_arch_prctl 0
#define __netbsd_powerpc32_has_arch_prctl 0
#define __netbsd_powerpc64_has_arch_prctl 0
#define __netbsd_riscv32_has_arch_prctl 0
#define __netbsd_riscv64_has_arch_prctl 0
#define __netbsd_sparc32_has_arch_prctl 0
#define __netbsd_sparc64_has_arch_prctl 0
#define __netbsd_vax_has_arch_prctl 0
#define __netbsd_x64_has_arch_prctl 0
#define __netbsd_x86_has_arch_prctl 0
#define __openbsd_generic_has_arch_prctl 0
#define __openbsd_x64_has_arch_prctl 0
#define __openbsd_x86_has_arch_prctl 0

/* check SYS_fdatasync */
#define __config_has_has_fdatasync 0
#define __darwin_arm64_has_fdatasync 1
#define __darwin_generic_has_fdatasync 1
#define __darwin_x64_has_fdatasync 1
#define __dragonfly_generic_has_fdatasync 1
#define __dragonfly_x64_has_fdatasync 1
#define __dragonfly_x86_has_fdatasync 1
#define __format_auxv_has_fdatasync 0
#define __format_elf_has_fdatasync 0
#define __format_em_has_fdatasync 0
#define __format_macho_has_fdatasync 0
#define __format_pe_has_fdatasync 0
#define __freebsd_generic_has_fdatasync 1
#define __freebsd_x64_has_fdatasync 1
#define __freebsd_x86_has_fdatasync 1
#define __linux_alpha_has_fdatasync 1
#define __linux_arc_has_fdatasync 1
#define __linux_arm32_has_fdatasync 1
#define __linux_arm64_has_fdatasync 1
#define __linux_csky_has_fdatasync 1
#define __linux_generic_has_fdatasync 1
#define __linux_hexagon_has_fdatasync 1
#define __linux_hppa_has_fdatasync 1
#define __linux_loongarch64_has_fdatasync 1
#define __linux_m68k_has_fdatasync 1
#define __linux_microblaze_has_fdatasync 1
#define __linux_mips32_has_fdatasync 1
#define __linux_mips64_has_fdatasync 1
#define __linux_nios2_has_fdatasync 1
#define __linux_or1k_has_fdatasync 1
#define __linux_powerpc32_has_fdatasync 1
#define __linux_powerpc64_has_fdatasync 1
#define __linux_riscv32_has_fdatasync 1
#define __linux_riscv64_has_fdatasync 1
#define __linux_s390x_has_fdatasync 1
#define __linux_sh4_has_fdatasync 1
#define __linux_sparc32_has_fdatasync 1
#define __linux_sparc64_has_fdatasync 1
#define __linux_x64_has_fdatasync 1
#define __linux_x86_has_fdatasync 1
#define __linux_xtensa_has_fdatasync 1
#define __netbsd_alpha_has_fdatasync 0
#define __netbsd_arm32_has_fdatasync 0
#define __netbsd_arm64_has_fdatasync 0
#define __netbsd_generic_has_fdatasync 0
#define __netbsd_hppa_has_fdatasync 0
#define __netbsd_ia64_has_fdatasync 0
#define __netbsd_powerpc32_has_fdatasync 0
#define __netbsd_powerpc64_has_fdatasync 0
#define __netbsd_riscv32_has_fdatasync 0
#define __netbsd_riscv64_has_fdatasync 0
#define __netbsd_sparc32_has_fdatasync 0
#define __netbsd_sparc64_has_fdatasync 0
#define __netbsd_vax_has_fdatasync 0
#define __netbsd_x64_has_fdatasync 0
#define __netbsd_x86_has_fdatasync 0
#define __openbsd_generic_has_fdatasync 0
#define __openbsd_x64_has_fdatasync 0
#define __openbsd_x86_has_fdatasync 0

/* check SYS_fstat */
#define __config_has_has_fstat 0
#define __darwin_arm64_has_fstat 1
#define __darwin_generic_has_fstat 1
#define __darwin_x64_has_fstat 1
#define __dragonfly_generic_has_fstat 0
#define __dragonfly_x64_has_fstat 0
#define __dragonfly_x86_has_fstat 0
#define __format_auxv_has_fstat 0
#define __format_elf_has_fstat 0
#define __format_em_has_fstat 0
#define __format_macho_has_fstat 0
#define __format_pe_has_fstat 0
#define __freebsd_generic_has_fstat 1
#define __freebsd_x64_has_fstat 1
#define __freebsd_x86_has_fstat 1
#define __linux_alpha_has_fstat 1
#define __linux_arc_has_fstat 1
#define __linux_arm32_has_fstat 1
#define __linux_arm64_has_fstat 1
#define __linux_csky_has_fstat 1
#define __linux_generic_has_fstat 1
#define __linux_hexagon_has_fstat 1
#define __linux_hppa_has_fstat 1
#define __linux_loongarch64_has_fstat 1
#define __linux_m68k_has_fstat 1
#define __linux_microblaze_has_fstat 1
#define __linux_mips32_has_fstat 1
#define __linux_mips64_has_fstat 1
#define __linux_nios2_has_fstat 1
#define __linux_or1k_has_fstat 1
#define __linux_powerpc32_has_fstat 1
#define __linux_powerpc64_has_fstat 1
#define __linux_riscv32_has_fstat 1
#define __linux_riscv64_has_fstat 1
#define __linux_s390x_has_fstat 1
#define __linux_sh4_has_fstat 1
#define __linux_sparc32_has_fstat 1
#define __linux_sparc64_has_fstat 1
#define __linux_x64_has_fstat 1
#define __linux_x86_has_fstat 1
#define __linux_xtensa_has_fstat 1
#define __netbsd_alpha_has_fstat 1
#define __netbsd_arm32_has_fstat 1
#define __netbsd_arm64_has_fstat 1
#define __netbsd_generic_has_fstat 1
#define __netbsd_hppa_has_fstat 1
#define __netbsd_ia64_has_fstat 1
#define __netbsd_powerpc32_has_fstat 1
#define __netbsd_powerpc64_has_fstat 1
#define __netbsd_riscv32_has_fstat 1
#define __netbsd_riscv64_has_fstat 1
#define __netbsd_sparc32_has_fstat 1
#define __netbsd_sparc64_has_fstat 1
#define __netbsd_vax_has_fstat 1
#define __netbsd_x64_has_fstat 1
#define __netbsd_x86_has_fstat 1
#define __openbsd_generic_has_fstat 1
#define __openbsd_x64_has_fstat 1
#define __openbsd_x86_has_fstat 1

/* check SYS_fstat64 */
#define __config_has_has_fstat64 0
#define __darwin_arm64_has_fstat64 0
#define __darwin_generic_has_fstat64 0
#define __darwin_x64_has_fstat64 0
#define __dragonfly_generic_has_fstat64 0
#define __dragonfly_x64_has_fstat64 0
#define __dragonfly_x86_has_fstat64 0
#define __format_auxv_has_fstat64 0
#define __format_elf_has_fstat64 0
#define __format_em_has_fstat64 0
#define __format_macho_has_fstat64 0
#define __format_pe_has_fstat64 0
#define __freebsd_generic_has_fstat64 0
#define __freebsd_x64_has_fstat64 0
#define __freebsd_x86_has_fstat64 0
#define __linux_alpha_has_fstat64 1
#define __linux_arc_has_fstat64 1
#define __linux_arm32_has_fstat64 1
#define __linux_arm64_has_fstat64 1
#define __linux_csky_has_fstat64 1
#define __linux_generic_has_fstat64 1
#define __linux_hexagon_has_fstat64 1
#define __linux_hppa_has_fstat64 1
#define __linux_loongarch64_has_fstat64 1
#define __linux_m68k_has_fstat64 1
#define __linux_microblaze_has_fstat64 1
#define __linux_mips32_has_fstat64 0
#define __linux_mips64_has_fstat64 0
#define __linux_nios2_has_fstat64 1
#define __linux_or1k_has_fstat64 1
#define __linux_powerpc32_has_fstat64 1
#define __linux_powerpc64_has_fstat64 1
#define __linux_riscv32_has_fstat64 1
#define __linux_riscv64_has_fstat64 1
#define __linux_s390x_has_fstat64 1
#define __linux_sh4_has_fstat64 1
#define __linux_sparc32_has_fstat64 1
#define __linux_sparc64_has_fstat64 1
#define __linux_x64_has_fstat64 0
#define __linux_x86_has_fstat64 1
#define __linux_xtensa_has_fstat64 1
#define __netbsd_alpha_has_fstat64 0
#define __netbsd_arm32_has_fstat64 0
#define __netbsd_arm64_has_fstat64 0
#define __netbsd_generic_has_fstat64 0
#define __netbsd_hppa_has_fstat64 0
#define __netbsd_ia64_has_fstat64 0
#define __netbsd_powerpc32_has_fstat64 0
#define __netbsd_powerpc64_has_fstat64 0
#define __netbsd_riscv32_has_fstat64 0
#define __netbsd_riscv64_has_fstat64 0
#define __netbsd_sparc32_has_fstat64 0
#define __netbsd_sparc64_has_fstat64 0
#define __netbsd_vax_has_fstat64 0
#define __netbsd_x64_has_fstat64 0
#define __netbsd_x86_has_fstat64 0
#define __openbsd_generic_has_fstat64 0
#define __openbsd_x64_has_fstat64 0
#define __openbsd_x86_has_fstat64 0

/* check SYS_futimens */
#define __config_has_has_futimens 0
#define __darwin_arm64_has_futimens 0
#define __darwin_generic_has_futimens 0
#define __darwin_x64_has_futimens 0
#define __dragonfly_generic_has_futimens 0
#define __dragonfly_x64_has_futimens 0
#define __dragonfly_x86_has_futimens 0
#define __format_auxv_has_futimens 0
#define __format_elf_has_futimens 0
#define __format_em_has_futimens 0
#define __format_macho_has_futimens 0
#define __format_pe_has_futimens 0
#define __freebsd_generic_has_futimens 1
#define __freebsd_x64_has_futimens 1
#define __freebsd_x86_has_futimens 1
#define __linux_alpha_has_futimens 0
#define __linux_arc_has_futimens 0
#define __linux_arm32_has_futimens 0
#define __linux_arm64_has_futimens 0
#define __linux_csky_has_futimens 0
#define __linux_generic_has_futimens 0
#define __linux_hexagon_has_futimens 0
#define __linux_hppa_has_futimens 0
#define __linux_loongarch64_has_futimens 0
#define __linux_m68k_has_futimens 0
#define __linux_microblaze_has_futimens 0
#define __linux_mips32_has_futimens 0
#define __linux_mips64_has_futimens 0
#define __linux_nios2_has_futimens 0
#define __linux_or1k_has_futimens 0
#define __linux_powerpc32_has_futimens 0
#define __linux_powerpc64_has_futimens 0
#define __linux_riscv32_has_futimens 0
#define __linux_riscv64_has_futimens 0
#define __linux_s390x_has_futimens 0
#define __linux_sh4_has_futimens 0
#define __linux_sparc32_has_futimens 0
#define __linux_sparc64_has_futimens 0
#define __linux_x64_has_futimens 0
#define __linux_x86_has_futimens 0
#define __linux_xtensa_has_futimens 0
#define __netbsd_alpha_has_futimens 1
#define __netbsd_arm32_has_futimens 1
#define __netbsd_arm64_has_futimens 1
#define __netbsd_generic_has_futimens 1
#define __netbsd_hppa_has_futimens 1
#define __netbsd_ia64_has_futimens 1
#define __netbsd_powerpc32_has_futimens 1
#define __netbsd_powerpc64_has_futimens 1
#define __netbsd_riscv32_has_futimens 1
#define __netbsd_riscv64_has_futimens 1
#define __netbsd_sparc32_has_futimens 1
#define __netbsd_sparc64_has_futimens 1
#define __netbsd_vax_has_futimens 1
#define __netbsd_x64_has_futimens 1
#define __netbsd_x86_has_futimens 1
#define __openbsd_generic_has_futimens 0
#define __openbsd_x64_has_futimens 0
#define __openbsd_x86_has_futimens 0

/* check SYS_gethostname */
#define __config_has_has_gethostname 0
#define __darwin_arm64_has_gethostname 0
#define __darwin_generic_has_gethostname 0
#define __darwin_x64_has_gethostname 0
#define __dragonfly_generic_has_gethostname 0
#define __dragonfly_x64_has_gethostname 0
#define __dragonfly_x86_has_gethostname 0
#define __format_auxv_has_gethostname 0
#define __format_elf_has_gethostname 0
#define __format_em_has_gethostname 0
#define __format_macho_has_gethostname 0
#define __format_pe_has_gethostname 0
#define __freebsd_generic_has_gethostname 1
#define __freebsd_x64_has_gethostname 1
#define __freebsd_x86_has_gethostname 1
#define __linux_alpha_has_gethostname 0
#define __linux_arc_has_gethostname 0
#define __linux_arm32_has_gethostname 0
#define __linux_arm64_has_gethostname 0
#define __linux_csky_has_gethostname 0
#define __linux_generic_has_gethostname 0
#define __linux_hexagon_has_gethostname 0
#define __linux_hppa_has_gethostname 0
#define __linux_loongarch64_has_gethostname 0
#define __linux_m68k_has_gethostname 0
#define __linux_microblaze_has_gethostname 0
#define __linux_mips32_has_gethostname 0
#define __linux_mips64_has_gethostname 0
#define __linux_nios2_has_gethostname 0
#define __linux_or1k_has_gethostname 0
#define __linux_powerpc32_has_gethostname 0
#define __linux_powerpc64_has_gethostname 0
#define __linux_riscv32_has_gethostname 0
#define __linux_riscv64_has_gethostname 0
#define __linux_s390x_has_gethostname 0
#define __linux_sh4_has_gethostname 0
#define __linux_sparc32_has_gethostname 0
#define __linux_sparc64_has_gethostname 0
#define __linux_x64_has_gethostname 0
#define __linux_x86_has_gethostname 0
#define __linux_xtensa_has_gethostname 0
#define __netbsd_alpha_has_gethostname 0
#define __netbsd_arm32_has_gethostname 0
#define __netbsd_arm64_has_gethostname 0
#define __netbsd_generic_has_gethostname 0
#define __netbsd_hppa_has_gethostname 0
#define __netbsd_ia64_has_gethostname 0
#define __netbsd_powerpc32_has_gethostname 0
#define __netbsd_powerpc64_has_gethostname 0
#define __netbsd_riscv32_has_gethostname 0
#define __netbsd_riscv64_has_gethostname 0
#define __netbsd_sparc32_has_gethostname 0
#define __netbsd_sparc64_has_gethostname 0
#define __netbsd_vax_has_gethostname 0
#define __netbsd_x64_has_gethostname 0
#define __netbsd_x86_has_gethostname 0
#define __openbsd_generic_has_gethostname 0
#define __openbsd_x64_has_gethostname 0
#define __openbsd_x86_has_gethostname 0

/* check SYS_ioctl */
#define __config_has_has_ioctl 0
#define __darwin_arm64_has_ioctl 0
#define __darwin_generic_has_ioctl 0
#define __darwin_x64_has_ioctl 0
#define __dragonfly_generic_has_ioctl 1
#define __dragonfly_x64_has_ioctl 1
#define __dragonfly_x86_has_ioctl 1
#define __format_auxv_has_ioctl 0
#define __format_elf_has_ioctl 0
#define __format_em_has_ioctl 0
#define __format_macho_has_ioctl 0
#define __format_pe_has_ioctl 0
#define __freebsd_generic_has_ioctl 1
#define __freebsd_x64_has_ioctl 1
#define __freebsd_x86_has_ioctl 1
#define __linux_alpha_has_ioctl 1
#define __linux_arc_has_ioctl 1
#define __linux_arm32_has_ioctl 1
#define __linux_arm64_has_ioctl 1
#define __linux_csky_has_ioctl 1
#define __linux_generic_has_ioctl 1
#define __linux_hexagon_has_ioctl 1
#define __linux_hppa_has_ioctl 1
#define __linux_loongarch64_has_ioctl 1
#define __linux_m68k_has_ioctl 1
#define __linux_microblaze_has_ioctl 1
#define __linux_mips32_has_ioctl 1
#define __linux_mips64_has_ioctl 1
#define __linux_nios2_has_ioctl 1
#define __linux_or1k_has_ioctl 1
#define __linux_powerpc32_has_ioctl 1
#define __linux_powerpc64_has_ioctl 1
#define __linux_riscv32_has_ioctl 1
#define __linux_riscv64_has_ioctl 1
#define __linux_s390x_has_ioctl 1
#define __linux_sh4_has_ioctl 1
#define __linux_sparc32_has_ioctl 1
#define __linux_sparc64_has_ioctl 1
#define __linux_x64_has_ioctl 1
#define __linux_x86_has_ioctl 1
#define __linux_xtensa_has_ioctl 1
#define __netbsd_alpha_has_ioctl 1
#define __netbsd_arm32_has_ioctl 1
#define __netbsd_arm64_has_ioctl 1
#define __netbsd_generic_has_ioctl 1
#define __netbsd_hppa_has_ioctl 1
#define __netbsd_ia64_has_ioctl 1
#define __netbsd_powerpc32_has_ioctl 1
#define __netbsd_powerpc64_has_ioctl 1
#define __netbsd_riscv32_has_ioctl 1
#define __netbsd_riscv64_has_ioctl 1
#define __netbsd_sparc32_has_ioctl 1
#define __netbsd_sparc64_has_ioctl 1
#define __netbsd_vax_has_ioctl 1
#define __netbsd_x64_has_ioctl 1
#define __netbsd_x86_has_ioctl 1
#define __openbsd_generic_has_ioctl 0
#define __openbsd_x64_has_ioctl 0
#define __openbsd_x86_has_ioctl 0

/* check SYS_lstat64 */
#define __config_has_has_lstat64 0
#define __darwin_arm64_has_lstat64 1
#define __darwin_generic_has_lstat64 1
#define __darwin_x64_has_lstat64 1
#define __dragonfly_generic_has_lstat64 0
#define __dragonfly_x64_has_lstat64 0
#define __dragonfly_x86_has_lstat64 0
#define __format_auxv_has_lstat64 0
#define __format_elf_has_lstat64 0
#define __format_em_has_lstat64 0
#define __format_macho_has_lstat64 0
#define __format_pe_has_lstat64 0
#define __freebsd_generic_has_lstat64 0
#define __freebsd_x64_has_lstat64 0
#define __freebsd_x86_has_lstat64 0
#define __linux_alpha_has_lstat64 0
#define __linux_arc_has_lstat64 0
#define __linux_arm32_has_lstat64 1
#define __linux_arm64_has_lstat64 0
#define __linux_csky_has_lstat64 0
#define __linux_generic_has_lstat64 0
#define __linux_hexagon_has_lstat64 0
#define __linux_hppa_has_lstat64 1
#define __linux_loongarch64_has_lstat64 0
#define __linux_m68k_has_lstat64 0
#define __linux_microblaze_has_lstat64 0
#define __linux_mips32_has_lstat64 0
#define __linux_mips64_has_lstat64 0
#define __linux_nios2_has_lstat64 0
#define __linux_or1k_has_lstat64 0
#define __linux_powerpc32_has_lstat64 1
#define __linux_powerpc64_has_lstat64 1
#define __linux_riscv32_has_lstat64 0
#define __linux_riscv64_has_lstat64 0
#define __linux_s390x_has_lstat64 1
#define __linux_sh4_has_lstat64 1
#define __linux_sparc32_has_lstat64 1
#define __linux_sparc64_has_lstat64 1
#define __linux_x64_has_lstat64 0
#define __linux_x86_has_lstat64 1
#define __linux_xtensa_has_lstat64 1
#define __netbsd_alpha_has_lstat64 0
#define __netbsd_arm32_has_lstat64 0
#define __netbsd_arm64_has_lstat64 0
#define __netbsd_generic_has_lstat64 0
#define __netbsd_hppa_has_lstat64 0
#define __netbsd_ia64_has_lstat64 0
#define __netbsd_powerpc32_has_lstat64 0
#define __netbsd_powerpc64_has_lstat64 0
#define __netbsd_riscv32_has_lstat64 0
#define __netbsd_riscv64_has_lstat64 0
#define __netbsd_sparc32_has_lstat64 0
#define __netbsd_sparc64_has_lstat64 0
#define __netbsd_vax_has_lstat64 0
#define __netbsd_x64_has_lstat64 0
#define __netbsd_x86_has_lstat64 0
#define __openbsd_generic_has_lstat64 0
#define __openbsd_x64_has_lstat64 0
#define __openbsd_x86_has_lstat64 0

/* check SYS_nanosleep */
#define __config_has_has_nanosleep 0
#define __darwin_arm64_has_nanosleep 0
#define __darwin_generic_has_nanosleep 0
#define __darwin_x64_has_nanosleep 0
#define __dragonfly_generic_has_nanosleep 1
#define __dragonfly_x64_has_nanosleep 1
#define __dragonfly_x86_has_nanosleep 1
#define __format_auxv_has_nanosleep 0
#define __format_elf_has_nanosleep 0
#define __format_em_has_nanosleep 0
#define __format_macho_has_nanosleep 0
#define __format_pe_has_nanosleep 0
#define __freebsd_generic_has_nanosleep 1
#define __freebsd_x64_has_nanosleep 1
#define __freebsd_x86_has_nanosleep 1
#define __linux_alpha_has_nanosleep 1
#define __linux_arc_has_nanosleep 1
#define __linux_arm32_has_nanosleep 1
#define __linux_arm64_has_nanosleep 1
#define __linux_csky_has_nanosleep 1
#define __linux_generic_has_nanosleep 1
#define __linux_hexagon_has_nanosleep 1
#define __linux_hppa_has_nanosleep 1
#define __linux_loongarch64_has_nanosleep 1
#define __linux_m68k_has_nanosleep 1
#define __linux_microblaze_has_nanosleep 1
#define __linux_mips32_has_nanosleep 1
#define __linux_mips64_has_nanosleep 1
#define __linux_nios2_has_nanosleep 1
#define __linux_or1k_has_nanosleep 1
#define __linux_powerpc32_has_nanosleep 1
#define __linux_powerpc64_has_nanosleep 1
#define __linux_riscv32_has_nanosleep 1
#define __linux_riscv64_has_nanosleep 1
#define __linux_s390x_has_nanosleep 1
#define __linux_sh4_has_nanosleep 1
#define __linux_sparc32_has_nanosleep 1
#define __linux_sparc64_has_nanosleep 1
#define __linux_x64_has_nanosleep 1
#define __linux_x86_has_nanosleep 1
#define __linux_xtensa_has_nanosleep 1
#define __netbsd_alpha_has_nanosleep 1
#define __netbsd_arm32_has_nanosleep 1
#define __netbsd_arm64_has_nanosleep 1
#define __netbsd_generic_has_nanosleep 1
#define __netbsd_hppa_has_nanosleep 1
#define __netbsd_ia64_has_nanosleep 1
#define __netbsd_powerpc32_has_nanosleep 1
#define __netbsd_powerpc64_has_nanosleep 1
#define __netbsd_riscv32_has_nanosleep 1
#define __netbsd_riscv64_has_nanosleep 1
#define __netbsd_sparc32_has_nanosleep 1
#define __netbsd_sparc64_has_nanosleep 1
#define __netbsd_vax_has_nanosleep 1
#define __netbsd_x64_has_nanosleep 1
#define __netbsd_x86_has_nanosleep 1
#define __openbsd_generic_has_nanosleep 0
#define __openbsd_x64_has_nanosleep 0
#define __openbsd_x86_has_nanosleep 0

/* check SYS_newfstatat */
#define __config_has_has_newfstatat 0
#define __darwin_arm64_has_newfstatat 0
#define __darwin_generic_has_newfstatat 0
#define __darwin_x64_has_newfstatat 0
#define __dragonfly_generic_has_newfstatat 0
#define __dragonfly_x64_has_newfstatat 0
#define __dragonfly_x86_has_newfstatat 0
#define __format_auxv_has_newfstatat 0
#define __format_elf_has_newfstatat 0
#define __format_em_has_newfstatat 0
#define __format_macho_has_newfstatat 0
#define __format_pe_has_newfstatat 0
#define __freebsd_generic_has_newfstatat 0
#define __freebsd_x64_has_newfstatat 0
#define __freebsd_x86_has_newfstatat 0
#define __linux_alpha_has_newfstatat 1
#define __linux_arc_has_newfstatat 1
#define __linux_arm32_has_newfstatat 0
#define __linux_arm64_has_newfstatat 1
#define __linux_csky_has_newfstatat 1
#define __linux_generic_has_newfstatat 1
#define __linux_hexagon_has_newfstatat 1
#define __linux_hppa_has_newfstatat 0
#define __linux_loongarch64_has_newfstatat 1
#define __linux_m68k_has_newfstatat 1
#define __linux_microblaze_has_newfstatat 1
#define __linux_mips32_has_newfstatat 1
#define __linux_mips64_has_newfstatat 1
#define __linux_nios2_has_newfstatat 1
#define __linux_or1k_has_newfstatat 1
#define __linux_powerpc32_has_newfstatat 1
#define __linux_powerpc64_has_newfstatat 1
#define __linux_riscv32_has_newfstatat 1
#define __linux_riscv64_has_newfstatat 1
#define __linux_s390x_has_newfstatat 1
#define __linux_sh4_has_newfstatat 0
#define __linux_sparc32_has_newfstatat 0
#define __linux_sparc64_has_newfstatat 0
#define __linux_x64_has_newfstatat 1
#define __linux_x86_has_newfstatat 0
#define __linux_xtensa_has_newfstatat 0
#define __netbsd_alpha_has_newfstatat 0
#define __netbsd_arm32_has_newfstatat 0
#define __netbsd_arm64_has_newfstatat 0
#define __netbsd_generic_has_newfstatat 0
#define __netbsd_hppa_has_newfstatat 0
#define __netbsd_ia64_has_newfstatat 0
#define __netbsd_powerpc32_has_newfstatat 0
#define __netbsd_powerpc64_has_newfstatat 0
#define __netbsd_riscv32_has_newfstatat 0
#define __netbsd_riscv64_has_newfstatat 0
#define __netbsd_sparc32_has_newfstatat 0
#define __netbsd_sparc64_has_newfstatat 0
#define __netbsd_vax_has_newfstatat 0
#define __netbsd_x64_has_newfstatat 0
#define __netbsd_x86_has_newfstatat 0
#define __openbsd_generic_has_newfstatat 0
#define __openbsd_x64_has_newfstatat 0
#define __openbsd_x86_has_newfstatat 0

/* check SYS_pause */
#define __config_has_has_pause 0
#define __darwin_arm64_has_pause 0
#define __darwin_generic_has_pause 0
#define __darwin_x64_has_pause 0
#define __dragonfly_generic_has_pause 0
#define __dragonfly_x64_has_pause 0
#define __dragonfly_x86_has_pause 0
#define __format_auxv_has_pause 0
#define __format_elf_has_pause 0
#define __format_em_has_pause 0
#define __format_macho_has_pause 0
#define __format_pe_has_pause 0
#define __freebsd_generic_has_pause 0
#define __freebsd_x64_has_pause 0
#define __freebsd_x86_has_pause 0
#define __linux_alpha_has_pause 0
#define __linux_arc_has_pause 0
#define __linux_arm32_has_pause 1
#define __linux_arm64_has_pause 0
#define __linux_csky_has_pause 0
#define __linux_generic_has_pause 0
#define __linux_hexagon_has_pause 0
#define __linux_hppa_has_pause 1
#define __linux_loongarch64_has_pause 0
#define __linux_m68k_has_pause 0
#define __linux_microblaze_has_pause 0
#define __linux_mips32_has_pause 1
#define __linux_mips64_has_pause 1
#define __linux_nios2_has_pause 0
#define __linux_or1k_has_pause 0
#define __linux_powerpc32_has_pause 1
#define __linux_powerpc64_has_pause 1
#define __linux_riscv32_has_pause 0
#define __linux_riscv64_has_pause 0
#define __linux_s390x_has_pause 1
#define __linux_sh4_has_pause 1
#define __linux_sparc32_has_pause 1
#define __linux_sparc64_has_pause 1
#define __linux_x64_has_pause 1
#define __linux_x86_has_pause 1
#define __linux_xtensa_has_pause 0
#define __netbsd_alpha_has_pause 0
#define __netbsd_arm32_has_pause 0
#define __netbsd_arm64_has_pause 0
#define __netbsd_generic_has_pause 0
#define __netbsd_hppa_has_pause 0
#define __netbsd_ia64_has_pause 0
#define __netbsd_powerpc32_has_pause 0
#define __netbsd_powerpc64_has_pause 0
#define __netbsd_riscv32_has_pause 0
#define __netbsd_riscv64_has_pause 0
#define __netbsd_sparc32_has_pause 0
#define __netbsd_sparc64_has_pause 0
#define __netbsd_vax_has_pause 0
#define __netbsd_x64_has_pause 0
#define __netbsd_x86_has_pause 0
#define __openbsd_generic_has_pause 0
#define __openbsd_x64_has_pause 0
#define __openbsd_x86_has_pause 0

/* check SYS_pipe */
#define __config_has_has_pipe 0
#define __darwin_arm64_has_pipe 0
#define __darwin_generic_has_pipe 0
#define __darwin_x64_has_pipe 0
#define __dragonfly_generic_has_pipe 0
#define __dragonfly_x64_has_pipe 0
#define __dragonfly_x86_has_pipe 0
#define __format_auxv_has_pipe 0
#define __format_elf_has_pipe 0
#define __format_em_has_pipe 0
#define __format_macho_has_pipe 0
#define __format_pe_has_pipe 0
#define __freebsd_generic_has_pipe 1
#define __freebsd_x64_has_pipe 1
#define __freebsd_x86_has_pipe 1
#define __linux_alpha_has_pipe 0
#define __linux_arc_has_pipe 0
#define __linux_arm32_has_pipe 1
#define __linux_arm64_has_pipe 0
#define __linux_csky_has_pipe 0
#define __linux_generic_has_pipe 0
#define __linux_hexagon_has_pipe 0
#define __linux_hppa_has_pipe 1
#define __linux_loongarch64_has_pipe 0
#define __linux_m68k_has_pipe 0
#define __linux_microblaze_has_pipe 0
#define __linux_mips32_has_pipe 1
#define __linux_mips64_has_pipe 1
#define __linux_nios2_has_pipe 0
#define __linux_or1k_has_pipe 0
#define __linux_powerpc32_has_pipe 1
#define __linux_powerpc64_has_pipe 1
#define __linux_riscv32_has_pipe 0
#define __linux_riscv64_has_pipe 0
#define __linux_s390x_has_pipe 1
#define __linux_sh4_has_pipe 1
#define __linux_sparc32_has_pipe 1
#define __linux_sparc64_has_pipe 1
#define __linux_x64_has_pipe 1
#define __linux_x86_has_pipe 1
#define __linux_xtensa_has_pipe 1
#define __netbsd_alpha_has_pipe 1
#define __netbsd_arm32_has_pipe 1
#define __netbsd_arm64_has_pipe 1
#define __netbsd_generic_has_pipe 1
#define __netbsd_hppa_has_pipe 1
#define __netbsd_ia64_has_pipe 1
#define __netbsd_powerpc32_has_pipe 1
#define __netbsd_powerpc64_has_pipe 1
#define __netbsd_riscv32_has_pipe 1
#define __netbsd_riscv64_has_pipe 1
#define __netbsd_sparc32_has_pipe 1
#define __netbsd_sparc64_has_pipe 1
#define __netbsd_vax_has_pipe 1
#define __netbsd_x64_has_pipe 1
#define __netbsd_x86_has_pipe 1
#define __openbsd_generic_has_pipe 1
#define __openbsd_x64_has_pipe 1
#define __openbsd_x86_has_pipe 1

/* check SYS_pipe2 */
#define __config_has_has_pipe2 0
#define __darwin_arm64_has_pipe2 0
#define __darwin_generic_has_pipe2 0
#define __darwin_x64_has_pipe2 0
#define __dragonfly_generic_has_pipe2 0
#define __dragonfly_x64_has_pipe2 0
#define __dragonfly_x86_has_pipe2 0
#define __format_auxv_has_pipe2 0
#define __format_elf_has_pipe2 0
#define __format_em_has_pipe2 0
#define __format_macho_has_pipe2 0
#define __format_pe_has_pipe2 0
#define __freebsd_generic_has_pipe2 1
#define __freebsd_x64_has_pipe2 1
#define __freebsd_x86_has_pipe2 1
#define __linux_alpha_has_pipe2 1
#define __linux_arc_has_pipe2 1
#define __linux_arm32_has_pipe2 1
#define __linux_arm64_has_pipe2 1
#define __linux_csky_has_pipe2 1
#define __linux_generic_has_pipe2 1
#define __linux_hexagon_has_pipe2 1
#define __linux_hppa_has_pipe2 1
#define __linux_loongarch64_has_pipe2 1
#define __linux_m68k_has_pipe2 1
#define __linux_microblaze_has_pipe2 1
#define __linux_mips32_has_pipe2 1
#define __linux_mips64_has_pipe2 1
#define __linux_nios2_has_pipe2 1
#define __linux_or1k_has_pipe2 1
#define __linux_powerpc32_has_pipe2 1
#define __linux_powerpc64_has_pipe2 1
#define __linux_riscv32_has_pipe2 1
#define __linux_riscv64_has_pipe2 1
#define __linux_s390x_has_pipe2 1
#define __linux_sh4_has_pipe2 1
#define __linux_sparc32_has_pipe2 1
#define __linux_sparc64_has_pipe2 1
#define __linux_x64_has_pipe2 1
#define __linux_x86_has_pipe2 1
#define __linux_xtensa_has_pipe2 1
#define __netbsd_alpha_has_pipe2 0
#define __netbsd_arm32_has_pipe2 0
#define __netbsd_arm64_has_pipe2 0
#define __netbsd_generic_has_pipe2 0
#define __netbsd_hppa_has_pipe2 0
#define __netbsd_ia64_has_pipe2 0
#define __netbsd_powerpc32_has_pipe2 0
#define __netbsd_powerpc64_has_pipe2 0
#define __netbsd_riscv32_has_pipe2 0
#define __netbsd_riscv64_has_pipe2 0
#define __netbsd_sparc32_has_pipe2 0
#define __netbsd_sparc64_has_pipe2 0
#define __netbsd_vax_has_pipe2 0
#define __netbsd_x64_has_pipe2 0
#define __netbsd_x86_has_pipe2 0
#define __openbsd_generic_has_pipe2 1
#define __openbsd_x64_has_pipe2 1
#define __openbsd_x86_has_pipe2 1

/* check SYS_sethostname */
#define __config_has_has_sethostname 0
#define __darwin_arm64_has_sethostname 0
#define __darwin_generic_has_sethostname 0
#define __darwin_x64_has_sethostname 0
#define __dragonfly_generic_has_sethostname 0
#define __dragonfly_x64_has_sethostname 0
#define __dragonfly_x86_has_sethostname 0
#define __format_auxv_has_sethostname 0
#define __format_elf_has_sethostname 0
#define __format_em_has_sethostname 0
#define __format_macho_has_sethostname 0
#define __format_pe_has_sethostname 0
#define __freebsd_generic_has_sethostname 1
#define __freebsd_x64_has_sethostname 1
#define __freebsd_x86_has_sethostname 1
#define __linux_alpha_has_sethostname 1
#define __linux_arc_has_sethostname 1
#define __linux_arm32_has_sethostname 1
#define __linux_arm64_has_sethostname 1
#define __linux_csky_has_sethostname 1
#define __linux_generic_has_sethostname 1
#define __linux_hexagon_has_sethostname 1
#define __linux_hppa_has_sethostname 1
#define __linux_loongarch64_has_sethostname 1
#define __linux_m68k_has_sethostname 1
#define __linux_microblaze_has_sethostname 1
#define __linux_mips32_has_sethostname 1
#define __linux_mips64_has_sethostname 1
#define __linux_nios2_has_sethostname 1
#define __linux_or1k_has_sethostname 1
#define __linux_powerpc32_has_sethostname 1
#define __linux_powerpc64_has_sethostname 1
#define __linux_riscv32_has_sethostname 1
#define __linux_riscv64_has_sethostname 1
#define __linux_s390x_has_sethostname 1
#define __linux_sh4_has_sethostname 1
#define __linux_sparc32_has_sethostname 1
#define __linux_sparc64_has_sethostname 1
#define __linux_x64_has_sethostname 1
#define __linux_x86_has_sethostname 1
#define __linux_xtensa_has_sethostname 1
#define __netbsd_alpha_has_sethostname 0
#define __netbsd_arm32_has_sethostname 0
#define __netbsd_arm64_has_sethostname 0
#define __netbsd_generic_has_sethostname 0
#define __netbsd_hppa_has_sethostname 0
#define __netbsd_ia64_has_sethostname 0
#define __netbsd_powerpc32_has_sethostname 0
#define __netbsd_powerpc64_has_sethostname 0
#define __netbsd_riscv32_has_sethostname 0
#define __netbsd_riscv64_has_sethostname 0
#define __netbsd_sparc32_has_sethostname 0
#define __netbsd_sparc64_has_sethostname 0
#define __netbsd_vax_has_sethostname 0
#define __netbsd_x64_has_sethostname 0
#define __netbsd_x86_has_sethostname 0
#define __openbsd_generic_has_sethostname 0
#define __openbsd_x64_has_sethostname 0
#define __openbsd_x86_has_sethostname 0

/* check SYS_stat64 */
#define __config_has_has_stat64 0
#define __darwin_arm64_has_stat64 1
#define __darwin_generic_has_stat64 1
#define __darwin_x64_has_stat64 1
#define __dragonfly_generic_has_stat64 0
#define __dragonfly_x64_has_stat64 0
#define __dragonfly_x86_has_stat64 0
#define __format_auxv_has_stat64 0
#define __format_elf_has_stat64 0
#define __format_em_has_stat64 0
#define __format_macho_has_stat64 0
#define __format_pe_has_stat64 0
#define __freebsd_generic_has_stat64 0
#define __freebsd_x64_has_stat64 0
#define __freebsd_x86_has_stat64 0
#define __linux_alpha_has_stat64 0
#define __linux_arc_has_stat64 0
#define __linux_arm32_has_stat64 1
#define __linux_arm64_has_stat64 0
#define __linux_csky_has_stat64 0
#define __linux_generic_has_stat64 0
#define __linux_hexagon_has_stat64 0
#define __linux_hppa_has_stat64 1
#define __linux_loongarch64_has_stat64 0
#define __linux_m68k_has_stat64 0
#define __linux_microblaze_has_stat64 0
#define __linux_mips32_has_stat64 0
#define __linux_mips64_has_stat64 0
#define __linux_nios2_has_stat64 0
#define __linux_or1k_has_stat64 0
#define __linux_powerpc32_has_stat64 1
#define __linux_powerpc64_has_stat64 1
#define __linux_riscv32_has_stat64 0
#define __linux_riscv64_has_stat64 0
#define __linux_s390x_has_stat64 1
#define __linux_sh4_has_stat64 1
#define __linux_sparc32_has_stat64 1
#define __linux_sparc64_has_stat64 1
#define __linux_x64_has_stat64 0
#define __linux_x86_has_stat64 1
#define __linux_xtensa_has_stat64 1
#define __netbsd_alpha_has_stat64 0
#define __netbsd_arm32_has_stat64 0
#define __netbsd_arm64_has_stat64 0
#define __netbsd_generic_has_stat64 0
#define __netbsd_hppa_has_stat64 0
#define __netbsd_ia64_has_stat64 0
#define __netbsd_powerpc32_has_stat64 0
#define __netbsd_powerpc64_has_stat64 0
#define __netbsd_riscv32_has_stat64 0
#define __netbsd_riscv64_has_stat64 0
#define __netbsd_sparc32_has_stat64 0
#define __netbsd_sparc64_has_stat64 0
#define __netbsd_vax_has_stat64 0
#define __netbsd_x64_has_stat64 0
#define __netbsd_x86_has_stat64 0
#define __openbsd_generic_has_stat64 0
#define __openbsd_x64_has_stat64 0
#define __openbsd_x86_has_stat64 0

/* check SYS_utimensat */
#define __config_has_has_utimensat 0
#define __darwin_arm64_has_utimensat 0
#define __darwin_generic_has_utimensat 0
#define __darwin_x64_has_utimensat 0
#define __dragonfly_generic_has_utimensat 1
#define __dragonfly_x64_has_utimensat 1
#define __dragonfly_x86_has_utimensat 1
#define __format_auxv_has_utimensat 0
#define __format_elf_has_utimensat 0
#define __format_em_has_utimensat 0
#define __format_macho_has_utimensat 0
#define __format_pe_has_utimensat 0
#define __freebsd_generic_has_utimensat 1
#define __freebsd_x64_has_utimensat 1
#define __freebsd_x86_has_utimensat 1
#define __linux_alpha_has_utimensat 1
#define __linux_arc_has_utimensat 1
#define __linux_arm32_has_utimensat 1
#define __linux_arm64_has_utimensat 1
#define __linux_csky_has_utimensat 1
#define __linux_generic_has_utimensat 1
#define __linux_hexagon_has_utimensat 1
#define __linux_hppa_has_utimensat 1
#define __linux_loongarch64_has_utimensat 1
#define __linux_m68k_has_utimensat 1
#define __linux_microblaze_has_utimensat 1
#define __linux_mips32_has_utimensat 1
#define __linux_mips64_has_utimensat 1
#define __linux_nios2_has_utimensat 1
#define __linux_or1k_has_utimensat 1
#define __linux_powerpc32_has_utimensat 1
#define __linux_powerpc64_has_utimensat 1
#define __linux_riscv32_has_utimensat 1
#define __linux_riscv64_has_utimensat 1
#define __linux_s390x_has_utimensat 1
#define __linux_sh4_has_utimensat 1
#define __linux_sparc32_has_utimensat 1
#define __linux_sparc64_has_utimensat 1
#define __linux_x64_has_utimensat 1
#define __linux_x86_has_utimensat 1
#define __linux_xtensa_has_utimensat 1
#define __netbsd_alpha_has_utimensat 1
#define __netbsd_arm32_has_utimensat 1
#define __netbsd_arm64_has_utimensat 1
#define __netbsd_generic_has_utimensat 1
#define __netbsd_hppa_has_utimensat 1
#define __netbsd_ia64_has_utimensat 1
#define __netbsd_powerpc32_has_utimensat 1
#define __netbsd_powerpc64_has_utimensat 1
#define __netbsd_riscv32_has_utimensat 1
#define __netbsd_riscv64_has_utimensat 1
#define __netbsd_sparc32_has_utimensat 1
#define __netbsd_sparc64_has_utimensat 1
#define __netbsd_vax_has_utimensat 1
#define __netbsd_x64_has_utimensat 1
#define __netbsd_x86_has_utimensat 1
#define __openbsd_generic_has_utimensat 0
#define __openbsd_x64_has_utimensat 0
#define __openbsd_x86_has_utimensat 0
