/**
 * JACLIBC SYSCALLS MATRIX  //  last updated: 2026-03-04 00:35:48 UTC
 */

/* check SYS_alarm */
#define __darwin_arm64_has_alarm 0
#define __darwin_generic_has_alarm 0
#define __darwin_x64_has_alarm 0
#define __dragonfly_generic_has_alarm 0
#define __dragonfly_x64_has_alarm 0
#define __dragonfly_x86_has_alarm 0
#define __freebsd_generic_has_alarm 0
#define __freebsd_x64_has_alarm 0
#define __freebsd_x86_has_alarm 0
#define __linux_alpha_has_alarm 0
#define __linux_arc_has_alarm 0
#define __linux_arm32_has_alarm 0
#define __linux_arm64_has_alarm 0
#define __linux_csky_has_alarm 0
#define __linux_generic_has_alarm 0
#define __linux_hexagon_has_alarm 0
#define __linux_hppa_has_alarm 1
#define __linux_loongarch64_has_alarm 0
#define __linux_m68k_has_alarm 0
#define __linux_microblaze_has_alarm 0
#define __linux_mips32_has_alarm 1
#define __linux_mips64_has_alarm 1
#define __linux_nios2_has_alarm 0
#define __linux_or1k_has_alarm 0
#define __linux_powerpc32_has_alarm 1
#define __linux_powerpc64_has_alarm 1
#define __linux_riscv32_has_alarm 0
#define __linux_riscv64_has_alarm 0
#define __linux_s390x_has_alarm 1
#define __linux_sh4_has_alarm 1
#define __linux_sparc32_has_alarm 1
#define __linux_sparc64_has_alarm 1
#define __linux_x64_has_alarm 1
#define __linux_x86_has_alarm 1
#define __linux_xtensa_has_alarm 0
#define __netbsd_alpha_has_alarm 0
#define __netbsd_arm32_has_alarm 0
#define __netbsd_arm64_has_alarm 0
#define __netbsd_generic_has_alarm 0
#define __netbsd_hppa_has_alarm 0
#define __netbsd_ia64_has_alarm 0
#define __netbsd_powerpc32_has_alarm 0
#define __netbsd_powerpc64_has_alarm 0
#define __netbsd_riscv32_has_alarm 0
#define __netbsd_riscv64_has_alarm 0
#define __netbsd_sparc32_has_alarm 0
#define __netbsd_sparc64_has_alarm 0
#define __netbsd_vax_has_alarm 0
#define __netbsd_x64_has_alarm 0
#define __netbsd_x86_has_alarm 0
#define __openbsd_generic_has_alarm 0
#define __openbsd_x64_has_alarm 0
#define __openbsd_x86_has_alarm 0

/* check SYS_chmod */
#define __darwin_arm64_has_chmod 1
#define __darwin_generic_has_chmod 1
#define __darwin_x64_has_chmod 1
#define __dragonfly_generic_has_chmod 0
#define __dragonfly_x64_has_chmod 0
#define __dragonfly_x86_has_chmod 0
#define __freebsd_generic_has_chmod 1
#define __freebsd_x64_has_chmod 1
#define __freebsd_x86_has_chmod 1
#define __linux_alpha_has_chmod 0
#define __linux_arc_has_chmod 0
#define __linux_arm32_has_chmod 1
#define __linux_arm64_has_chmod 0
#define __linux_csky_has_chmod 0
#define __linux_generic_has_chmod 0
#define __linux_hexagon_has_chmod 0
#define __linux_hppa_has_chmod 1
#define __linux_loongarch64_has_chmod 0
#define __linux_m68k_has_chmod 0
#define __linux_microblaze_has_chmod 0
#define __linux_mips32_has_chmod 1
#define __linux_mips64_has_chmod 1
#define __linux_nios2_has_chmod 0
#define __linux_or1k_has_chmod 0
#define __linux_powerpc32_has_chmod 1
#define __linux_powerpc64_has_chmod 1
#define __linux_riscv32_has_chmod 0
#define __linux_riscv64_has_chmod 0
#define __linux_s390x_has_chmod 1
#define __linux_sh4_has_chmod 1
#define __linux_sparc32_has_chmod 1
#define __linux_sparc64_has_chmod 1
#define __linux_x64_has_chmod 1
#define __linux_x86_has_chmod 1
#define __linux_xtensa_has_chmod 1
#define __netbsd_alpha_has_chmod 0
#define __netbsd_arm32_has_chmod 0
#define __netbsd_arm64_has_chmod 0
#define __netbsd_generic_has_chmod 0
#define __netbsd_hppa_has_chmod 0
#define __netbsd_ia64_has_chmod 0
#define __netbsd_powerpc32_has_chmod 0
#define __netbsd_powerpc64_has_chmod 0
#define __netbsd_riscv32_has_chmod 0
#define __netbsd_riscv64_has_chmod 0
#define __netbsd_sparc32_has_chmod 0
#define __netbsd_sparc64_has_chmod 0
#define __netbsd_vax_has_chmod 0
#define __netbsd_x64_has_chmod 0
#define __netbsd_x86_has_chmod 0
#define __openbsd_generic_has_chmod 1
#define __openbsd_x64_has_chmod 1
#define __openbsd_x86_has_chmod 1

/* check SYS_fadvise64_64 */
#define __darwin_arm64_has_fadvise64_64 0
#define __darwin_generic_has_fadvise64_64 0
#define __darwin_x64_has_fadvise64_64 0
#define __dragonfly_generic_has_fadvise64_64 0
#define __dragonfly_x64_has_fadvise64_64 0
#define __dragonfly_x86_has_fadvise64_64 0
#define __freebsd_generic_has_fadvise64_64 0
#define __freebsd_x64_has_fadvise64_64 0
#define __freebsd_x86_has_fadvise64_64 0
#define __linux_alpha_has_fadvise64_64 1
#define __linux_arc_has_fadvise64_64 1
#define __linux_arm32_has_fadvise64_64 0
#define __linux_arm64_has_fadvise64_64 1
#define __linux_csky_has_fadvise64_64 1
#define __linux_generic_has_fadvise64_64 1
#define __linux_hexagon_has_fadvise64_64 1
#define __linux_hppa_has_fadvise64_64 1
#define __linux_loongarch64_has_fadvise64_64 1
#define __linux_m68k_has_fadvise64_64 1
#define __linux_microblaze_has_fadvise64_64 1
#define __linux_mips32_has_fadvise64_64 0
#define __linux_mips64_has_fadvise64_64 0
#define __linux_nios2_has_fadvise64_64 1
#define __linux_or1k_has_fadvise64_64 1
#define __linux_powerpc32_has_fadvise64_64 1
#define __linux_powerpc64_has_fadvise64_64 1
#define __linux_riscv32_has_fadvise64_64 1
#define __linux_riscv64_has_fadvise64_64 1
#define __linux_s390x_has_fadvise64_64 1
#define __linux_sh4_has_fadvise64_64 1
#define __linux_sparc32_has_fadvise64_64 1
#define __linux_sparc64_has_fadvise64_64 1
#define __linux_x64_has_fadvise64_64 0
#define __linux_x86_has_fadvise64_64 1
#define __linux_xtensa_has_fadvise64_64 1
#define __netbsd_alpha_has_fadvise64_64 0
#define __netbsd_arm32_has_fadvise64_64 0
#define __netbsd_arm64_has_fadvise64_64 0
#define __netbsd_generic_has_fadvise64_64 0
#define __netbsd_hppa_has_fadvise64_64 0
#define __netbsd_ia64_has_fadvise64_64 0
#define __netbsd_powerpc32_has_fadvise64_64 0
#define __netbsd_powerpc64_has_fadvise64_64 0
#define __netbsd_riscv32_has_fadvise64_64 0
#define __netbsd_riscv64_has_fadvise64_64 0
#define __netbsd_sparc32_has_fadvise64_64 0
#define __netbsd_sparc64_has_fadvise64_64 0
#define __netbsd_vax_has_fadvise64_64 0
#define __netbsd_x64_has_fadvise64_64 0
#define __netbsd_x86_has_fadvise64_64 0
#define __openbsd_generic_has_fadvise64_64 0
#define __openbsd_x64_has_fadvise64_64 0
#define __openbsd_x86_has_fadvise64_64 0

/* check SYS_fallocate */
#define __darwin_arm64_has_fallocate 0
#define __darwin_generic_has_fallocate 0
#define __darwin_x64_has_fallocate 0
#define __dragonfly_generic_has_fallocate 0
#define __dragonfly_x64_has_fallocate 0
#define __dragonfly_x86_has_fallocate 0
#define __freebsd_generic_has_fallocate 0
#define __freebsd_x64_has_fallocate 0
#define __freebsd_x86_has_fallocate 0
#define __linux_alpha_has_fallocate 1
#define __linux_arc_has_fallocate 1
#define __linux_arm32_has_fallocate 1
#define __linux_arm64_has_fallocate 1
#define __linux_csky_has_fallocate 1
#define __linux_generic_has_fallocate 1
#define __linux_hexagon_has_fallocate 1
#define __linux_hppa_has_fallocate 1
#define __linux_loongarch64_has_fallocate 1
#define __linux_m68k_has_fallocate 1
#define __linux_microblaze_has_fallocate 1
#define __linux_mips32_has_fallocate 1
#define __linux_mips64_has_fallocate 1
#define __linux_nios2_has_fallocate 1
#define __linux_or1k_has_fallocate 1
#define __linux_powerpc32_has_fallocate 1
#define __linux_powerpc64_has_fallocate 1
#define __linux_riscv32_has_fallocate 1
#define __linux_riscv64_has_fallocate 1
#define __linux_s390x_has_fallocate 1
#define __linux_sh4_has_fallocate 1
#define __linux_sparc32_has_fallocate 1
#define __linux_sparc64_has_fallocate 1
#define __linux_x64_has_fallocate 1
#define __linux_x86_has_fallocate 1
#define __linux_xtensa_has_fallocate 1
#define __netbsd_alpha_has_fallocate 0
#define __netbsd_arm32_has_fallocate 0
#define __netbsd_arm64_has_fallocate 0
#define __netbsd_generic_has_fallocate 0
#define __netbsd_hppa_has_fallocate 0
#define __netbsd_ia64_has_fallocate 0
#define __netbsd_powerpc32_has_fallocate 0
#define __netbsd_powerpc64_has_fallocate 0
#define __netbsd_riscv32_has_fallocate 0
#define __netbsd_riscv64_has_fallocate 0
#define __netbsd_sparc32_has_fallocate 0
#define __netbsd_sparc64_has_fallocate 0
#define __netbsd_vax_has_fallocate 0
#define __netbsd_x64_has_fallocate 0
#define __netbsd_x86_has_fallocate 0
#define __openbsd_generic_has_fallocate 0
#define __openbsd_x64_has_fallocate 0
#define __openbsd_x86_has_fallocate 0

/* check SYS_fchmod */
#define __darwin_arm64_has_fchmod 1
#define __darwin_generic_has_fchmod 1
#define __darwin_x64_has_fchmod 1
#define __dragonfly_generic_has_fchmod 1
#define __dragonfly_x64_has_fchmod 1
#define __dragonfly_x86_has_fchmod 1
#define __freebsd_generic_has_fchmod 1
#define __freebsd_x64_has_fchmod 1
#define __freebsd_x86_has_fchmod 1
#define __linux_alpha_has_fchmod 1
#define __linux_arc_has_fchmod 1
#define __linux_arm32_has_fchmod 1
#define __linux_arm64_has_fchmod 1
#define __linux_csky_has_fchmod 1
#define __linux_generic_has_fchmod 1
#define __linux_hexagon_has_fchmod 1
#define __linux_hppa_has_fchmod 1
#define __linux_loongarch64_has_fchmod 1
#define __linux_m68k_has_fchmod 1
#define __linux_microblaze_has_fchmod 1
#define __linux_mips32_has_fchmod 1
#define __linux_mips64_has_fchmod 1
#define __linux_nios2_has_fchmod 1
#define __linux_or1k_has_fchmod 1
#define __linux_powerpc32_has_fchmod 1
#define __linux_powerpc64_has_fchmod 1
#define __linux_riscv32_has_fchmod 1
#define __linux_riscv64_has_fchmod 1
#define __linux_s390x_has_fchmod 1
#define __linux_sh4_has_fchmod 1
#define __linux_sparc32_has_fchmod 1
#define __linux_sparc64_has_fchmod 1
#define __linux_x64_has_fchmod 1
#define __linux_x86_has_fchmod 1
#define __linux_xtensa_has_fchmod 1
#define __netbsd_alpha_has_fchmod 1
#define __netbsd_arm32_has_fchmod 1
#define __netbsd_arm64_has_fchmod 1
#define __netbsd_generic_has_fchmod 1
#define __netbsd_hppa_has_fchmod 1
#define __netbsd_ia64_has_fchmod 1
#define __netbsd_powerpc32_has_fchmod 1
#define __netbsd_powerpc64_has_fchmod 1
#define __netbsd_riscv32_has_fchmod 1
#define __netbsd_riscv64_has_fchmod 1
#define __netbsd_sparc32_has_fchmod 1
#define __netbsd_sparc64_has_fchmod 1
#define __netbsd_vax_has_fchmod 1
#define __netbsd_x64_has_fchmod 1
#define __netbsd_x86_has_fchmod 1
#define __openbsd_generic_has_fchmod 1
#define __openbsd_x64_has_fchmod 1
#define __openbsd_x86_has_fchmod 1

/* check SYS_fchmodat */
#define __darwin_arm64_has_fchmodat 1
#define __darwin_generic_has_fchmodat 1
#define __darwin_x64_has_fchmodat 1
#define __dragonfly_generic_has_fchmodat 1
#define __dragonfly_x64_has_fchmodat 1
#define __dragonfly_x86_has_fchmodat 1
#define __freebsd_generic_has_fchmodat 1
#define __freebsd_x64_has_fchmodat 1
#define __freebsd_x86_has_fchmodat 1
#define __linux_alpha_has_fchmodat 1
#define __linux_arc_has_fchmodat 1
#define __linux_arm32_has_fchmodat 1
#define __linux_arm64_has_fchmodat 1
#define __linux_csky_has_fchmodat 1
#define __linux_generic_has_fchmodat 1
#define __linux_hexagon_has_fchmodat 1
#define __linux_hppa_has_fchmodat 1
#define __linux_loongarch64_has_fchmodat 1
#define __linux_m68k_has_fchmodat 1
#define __linux_microblaze_has_fchmodat 1
#define __linux_mips32_has_fchmodat 1
#define __linux_mips64_has_fchmodat 1
#define __linux_nios2_has_fchmodat 1
#define __linux_or1k_has_fchmodat 1
#define __linux_powerpc32_has_fchmodat 1
#define __linux_powerpc64_has_fchmodat 1
#define __linux_riscv32_has_fchmodat 1
#define __linux_riscv64_has_fchmodat 1
#define __linux_s390x_has_fchmodat 1
#define __linux_sh4_has_fchmodat 1
#define __linux_sparc32_has_fchmodat 1
#define __linux_sparc64_has_fchmodat 1
#define __linux_x64_has_fchmodat 1
#define __linux_x86_has_fchmodat 1
#define __linux_xtensa_has_fchmodat 1
#define __netbsd_alpha_has_fchmodat 1
#define __netbsd_arm32_has_fchmodat 1
#define __netbsd_arm64_has_fchmodat 1
#define __netbsd_generic_has_fchmodat 1
#define __netbsd_hppa_has_fchmodat 1
#define __netbsd_ia64_has_fchmodat 1
#define __netbsd_powerpc32_has_fchmodat 1
#define __netbsd_powerpc64_has_fchmodat 1
#define __netbsd_riscv32_has_fchmodat 1
#define __netbsd_riscv64_has_fchmodat 1
#define __netbsd_sparc32_has_fchmodat 1
#define __netbsd_sparc64_has_fchmodat 1
#define __netbsd_vax_has_fchmodat 1
#define __netbsd_x64_has_fchmodat 1
#define __netbsd_x86_has_fchmodat 1
#define __openbsd_generic_has_fchmodat 0
#define __openbsd_x64_has_fchmodat 0
#define __openbsd_x86_has_fchmodat 0

/* check SYS_fcntl64 */
#define __darwin_arm64_has_fcntl64 0
#define __darwin_generic_has_fcntl64 0
#define __darwin_x64_has_fcntl64 0
#define __dragonfly_generic_has_fcntl64 0
#define __dragonfly_x64_has_fcntl64 0
#define __dragonfly_x86_has_fcntl64 0
#define __freebsd_generic_has_fcntl64 0
#define __freebsd_x64_has_fcntl64 0
#define __freebsd_x86_has_fcntl64 0
#define __linux_alpha_has_fcntl64 1
#define __linux_arc_has_fcntl64 1
#define __linux_arm32_has_fcntl64 1
#define __linux_arm64_has_fcntl64 1
#define __linux_csky_has_fcntl64 1
#define __linux_generic_has_fcntl64 1
#define __linux_hexagon_has_fcntl64 1
#define __linux_hppa_has_fcntl64 1
#define __linux_loongarch64_has_fcntl64 1
#define __linux_m68k_has_fcntl64 1
#define __linux_microblaze_has_fcntl64 1
#define __linux_mips32_has_fcntl64 1
#define __linux_mips64_has_fcntl64 0
#define __linux_nios2_has_fcntl64 1
#define __linux_or1k_has_fcntl64 1
#define __linux_powerpc32_has_fcntl64 1
#define __linux_powerpc64_has_fcntl64 1
#define __linux_riscv32_has_fcntl64 1
#define __linux_riscv64_has_fcntl64 1
#define __linux_s390x_has_fcntl64 1
#define __linux_sh4_has_fcntl64 1
#define __linux_sparc32_has_fcntl64 1
#define __linux_sparc64_has_fcntl64 1
#define __linux_x64_has_fcntl64 0
#define __linux_x86_has_fcntl64 1
#define __linux_xtensa_has_fcntl64 1
#define __netbsd_alpha_has_fcntl64 0
#define __netbsd_arm32_has_fcntl64 0
#define __netbsd_arm64_has_fcntl64 0
#define __netbsd_generic_has_fcntl64 0
#define __netbsd_hppa_has_fcntl64 0
#define __netbsd_ia64_has_fcntl64 0
#define __netbsd_powerpc32_has_fcntl64 0
#define __netbsd_powerpc64_has_fcntl64 0
#define __netbsd_riscv32_has_fcntl64 0
#define __netbsd_riscv64_has_fcntl64 0
#define __netbsd_sparc32_has_fcntl64 0
#define __netbsd_sparc64_has_fcntl64 0
#define __netbsd_vax_has_fcntl64 0
#define __netbsd_x64_has_fcntl64 0
#define __netbsd_x86_has_fcntl64 0
#define __openbsd_generic_has_fcntl64 0
#define __openbsd_x64_has_fcntl64 0
#define __openbsd_x86_has_fcntl64 0

/* check SYS_fdatasync */
#define __darwin_arm64_has_fdatasync 1
#define __darwin_generic_has_fdatasync 1
#define __darwin_x64_has_fdatasync 1
#define __dragonfly_generic_has_fdatasync 1
#define __dragonfly_x64_has_fdatasync 1
#define __dragonfly_x86_has_fdatasync 1
#define __freebsd_generic_has_fdatasync 1
#define __freebsd_x64_has_fdatasync 1
#define __freebsd_x86_has_fdatasync 1
#define __linux_alpha_has_fdatasync 1
#define __linux_arc_has_fdatasync 1
#define __linux_arm32_has_fdatasync 1
#define __linux_arm64_has_fdatasync 1
#define __linux_csky_has_fdatasync 1
#define __linux_generic_has_fdatasync 1
#define __linux_hexagon_has_fdatasync 1
#define __linux_hppa_has_fdatasync 1
#define __linux_loongarch64_has_fdatasync 1
#define __linux_m68k_has_fdatasync 1
#define __linux_microblaze_has_fdatasync 1
#define __linux_mips32_has_fdatasync 1
#define __linux_mips64_has_fdatasync 1
#define __linux_nios2_has_fdatasync 1
#define __linux_or1k_has_fdatasync 1
#define __linux_powerpc32_has_fdatasync 1
#define __linux_powerpc64_has_fdatasync 1
#define __linux_riscv32_has_fdatasync 1
#define __linux_riscv64_has_fdatasync 1
#define __linux_s390x_has_fdatasync 1
#define __linux_sh4_has_fdatasync 1
#define __linux_sparc32_has_fdatasync 1
#define __linux_sparc64_has_fdatasync 1
#define __linux_x64_has_fdatasync 1
#define __linux_x86_has_fdatasync 1
#define __linux_xtensa_has_fdatasync 1
#define __netbsd_alpha_has_fdatasync 0
#define __netbsd_arm32_has_fdatasync 0
#define __netbsd_arm64_has_fdatasync 0
#define __netbsd_generic_has_fdatasync 0
#define __netbsd_hppa_has_fdatasync 0
#define __netbsd_ia64_has_fdatasync 0
#define __netbsd_powerpc32_has_fdatasync 0
#define __netbsd_powerpc64_has_fdatasync 0
#define __netbsd_riscv32_has_fdatasync 0
#define __netbsd_riscv64_has_fdatasync 0
#define __netbsd_sparc32_has_fdatasync 0
#define __netbsd_sparc64_has_fdatasync 0
#define __netbsd_vax_has_fdatasync 0
#define __netbsd_x64_has_fdatasync 0
#define __netbsd_x86_has_fdatasync 0
#define __openbsd_generic_has_fdatasync 0
#define __openbsd_x64_has_fdatasync 0
#define __openbsd_x86_has_fdatasync 0

/* check SYS_fstat */
#define __darwin_arm64_has_fstat 1
#define __darwin_generic_has_fstat 1
#define __darwin_x64_has_fstat 1
#define __dragonfly_generic_has_fstat 0
#define __dragonfly_x64_has_fstat 0
#define __dragonfly_x86_has_fstat 0
#define __freebsd_generic_has_fstat 1
#define __freebsd_x64_has_fstat 1
#define __freebsd_x86_has_fstat 1
#define __linux_alpha_has_fstat 1
#define __linux_arc_has_fstat 1
#define __linux_arm32_has_fstat 1
#define __linux_arm64_has_fstat 1
#define __linux_csky_has_fstat 1
#define __linux_generic_has_fstat 1
#define __linux_hexagon_has_fstat 1
#define __linux_hppa_has_fstat 1
#define __linux_loongarch64_has_fstat 1
#define __linux_m68k_has_fstat 1
#define __linux_microblaze_has_fstat 1
#define __linux_mips32_has_fstat 1
#define __linux_mips64_has_fstat 1
#define __linux_nios2_has_fstat 1
#define __linux_or1k_has_fstat 1
#define __linux_powerpc32_has_fstat 1
#define __linux_powerpc64_has_fstat 1
#define __linux_riscv32_has_fstat 1
#define __linux_riscv64_has_fstat 1
#define __linux_s390x_has_fstat 1
#define __linux_sh4_has_fstat 1
#define __linux_sparc32_has_fstat 1
#define __linux_sparc64_has_fstat 1
#define __linux_x64_has_fstat 1
#define __linux_x86_has_fstat 1
#define __linux_xtensa_has_fstat 1
#define __netbsd_alpha_has_fstat 1
#define __netbsd_arm32_has_fstat 1
#define __netbsd_arm64_has_fstat 1
#define __netbsd_generic_has_fstat 1
#define __netbsd_hppa_has_fstat 1
#define __netbsd_ia64_has_fstat 1
#define __netbsd_powerpc32_has_fstat 1
#define __netbsd_powerpc64_has_fstat 1
#define __netbsd_riscv32_has_fstat 1
#define __netbsd_riscv64_has_fstat 1
#define __netbsd_sparc32_has_fstat 1
#define __netbsd_sparc64_has_fstat 1
#define __netbsd_vax_has_fstat 1
#define __netbsd_x64_has_fstat 1
#define __netbsd_x86_has_fstat 1
#define __openbsd_generic_has_fstat 1
#define __openbsd_x64_has_fstat 1
#define __openbsd_x86_has_fstat 1

/* check SYS_fstat64 */
#define __darwin_arm64_has_fstat64 0
#define __darwin_generic_has_fstat64 0
#define __darwin_x64_has_fstat64 0
#define __dragonfly_generic_has_fstat64 0
#define __dragonfly_x64_has_fstat64 0
#define __dragonfly_x86_has_fstat64 0
#define __freebsd_generic_has_fstat64 0
#define __freebsd_x64_has_fstat64 0
#define __freebsd_x86_has_fstat64 0
#define __linux_alpha_has_fstat64 1
#define __linux_arc_has_fstat64 1
#define __linux_arm32_has_fstat64 1
#define __linux_arm64_has_fstat64 1
#define __linux_csky_has_fstat64 1
#define __linux_generic_has_fstat64 1
#define __linux_hexagon_has_fstat64 1
#define __linux_hppa_has_fstat64 1
#define __linux_loongarch64_has_fstat64 1
#define __linux_m68k_has_fstat64 1
#define __linux_microblaze_has_fstat64 1
#define __linux_mips32_has_fstat64 0
#define __linux_mips64_has_fstat64 0
#define __linux_nios2_has_fstat64 1
#define __linux_or1k_has_fstat64 1
#define __linux_powerpc32_has_fstat64 1
#define __linux_powerpc64_has_fstat64 1
#define __linux_riscv32_has_fstat64 1
#define __linux_riscv64_has_fstat64 1
#define __linux_s390x_has_fstat64 1
#define __linux_sh4_has_fstat64 1
#define __linux_sparc32_has_fstat64 1
#define __linux_sparc64_has_fstat64 1
#define __linux_x64_has_fstat64 0
#define __linux_x86_has_fstat64 1
#define __linux_xtensa_has_fstat64 1
#define __netbsd_alpha_has_fstat64 0
#define __netbsd_arm32_has_fstat64 0
#define __netbsd_arm64_has_fstat64 0
#define __netbsd_generic_has_fstat64 0
#define __netbsd_hppa_has_fstat64 0
#define __netbsd_ia64_has_fstat64 0
#define __netbsd_powerpc32_has_fstat64 0
#define __netbsd_powerpc64_has_fstat64 0
#define __netbsd_riscv32_has_fstat64 0
#define __netbsd_riscv64_has_fstat64 0
#define __netbsd_sparc32_has_fstat64 0
#define __netbsd_sparc64_has_fstat64 0
#define __netbsd_vax_has_fstat64 0
#define __netbsd_x64_has_fstat64 0
#define __netbsd_x86_has_fstat64 0
#define __openbsd_generic_has_fstat64 0
#define __openbsd_x64_has_fstat64 0
#define __openbsd_x86_has_fstat64 0

/* check SYS_futimens */
#define __darwin_arm64_has_futimens 0
#define __darwin_generic_has_futimens 0
#define __darwin_x64_has_futimens 0
#define __dragonfly_generic_has_futimens 0
#define __dragonfly_x64_has_futimens 0
#define __dragonfly_x86_has_futimens 0
#define __freebsd_generic_has_futimens 1
#define __freebsd_x64_has_futimens 1
#define __freebsd_x86_has_futimens 1
#define __linux_alpha_has_futimens 0
#define __linux_arc_has_futimens 0
#define __linux_arm32_has_futimens 0
#define __linux_arm64_has_futimens 0
#define __linux_csky_has_futimens 0
#define __linux_generic_has_futimens 0
#define __linux_hexagon_has_futimens 0
#define __linux_hppa_has_futimens 0
#define __linux_loongarch64_has_futimens 0
#define __linux_m68k_has_futimens 0
#define __linux_microblaze_has_futimens 0
#define __linux_mips32_has_futimens 0
#define __linux_mips64_has_futimens 0
#define __linux_nios2_has_futimens 0
#define __linux_or1k_has_futimens 0
#define __linux_powerpc32_has_futimens 0
#define __linux_powerpc64_has_futimens 0
#define __linux_riscv32_has_futimens 0
#define __linux_riscv64_has_futimens 0
#define __linux_s390x_has_futimens 0
#define __linux_sh4_has_futimens 0
#define __linux_sparc32_has_futimens 0
#define __linux_sparc64_has_futimens 0
#define __linux_x64_has_futimens 0
#define __linux_x86_has_futimens 0
#define __linux_xtensa_has_futimens 0
#define __netbsd_alpha_has_futimens 1
#define __netbsd_arm32_has_futimens 1
#define __netbsd_arm64_has_futimens 1
#define __netbsd_generic_has_futimens 1
#define __netbsd_hppa_has_futimens 1
#define __netbsd_ia64_has_futimens 1
#define __netbsd_powerpc32_has_futimens 1
#define __netbsd_powerpc64_has_futimens 1
#define __netbsd_riscv32_has_futimens 1
#define __netbsd_riscv64_has_futimens 1
#define __netbsd_sparc32_has_futimens 1
#define __netbsd_sparc64_has_futimens 1
#define __netbsd_vax_has_futimens 1
#define __netbsd_x64_has_futimens 1
#define __netbsd_x86_has_futimens 1
#define __openbsd_generic_has_futimens 0
#define __openbsd_x64_has_futimens 0
#define __openbsd_x86_has_futimens 0

/* check SYS_futimes */
#define __darwin_arm64_has_futimes 1
#define __darwin_generic_has_futimes 1
#define __darwin_x64_has_futimes 1
#define __dragonfly_generic_has_futimes 0
#define __dragonfly_x64_has_futimes 0
#define __dragonfly_x86_has_futimes 0
#define __freebsd_generic_has_futimes 1
#define __freebsd_x64_has_futimes 1
#define __freebsd_x86_has_futimes 1
#define __linux_alpha_has_futimes 0
#define __linux_arc_has_futimes 0
#define __linux_arm32_has_futimes 0
#define __linux_arm64_has_futimes 0
#define __linux_csky_has_futimes 0
#define __linux_generic_has_futimes 0
#define __linux_hexagon_has_futimes 0
#define __linux_hppa_has_futimes 0
#define __linux_loongarch64_has_futimes 0
#define __linux_m68k_has_futimes 0
#define __linux_microblaze_has_futimes 0
#define __linux_mips32_has_futimes 0
#define __linux_mips64_has_futimes 0
#define __linux_nios2_has_futimes 0
#define __linux_or1k_has_futimes 0
#define __linux_powerpc32_has_futimes 0
#define __linux_powerpc64_has_futimes 0
#define __linux_riscv32_has_futimes 0
#define __linux_riscv64_has_futimes 0
#define __linux_s390x_has_futimes 0
#define __linux_sh4_has_futimes 0
#define __linux_sparc32_has_futimes 0
#define __linux_sparc64_has_futimes 0
#define __linux_x64_has_futimes 0
#define __linux_x86_has_futimes 0
#define __linux_xtensa_has_futimes 0
#define __netbsd_alpha_has_futimes 1
#define __netbsd_arm32_has_futimes 1
#define __netbsd_arm64_has_futimes 1
#define __netbsd_generic_has_futimes 1
#define __netbsd_hppa_has_futimes 1
#define __netbsd_ia64_has_futimes 1
#define __netbsd_powerpc32_has_futimes 1
#define __netbsd_powerpc64_has_futimes 1
#define __netbsd_riscv32_has_futimes 1
#define __netbsd_riscv64_has_futimes 1
#define __netbsd_sparc32_has_futimes 1
#define __netbsd_sparc64_has_futimes 1
#define __netbsd_vax_has_futimes 1
#define __netbsd_x64_has_futimes 1
#define __netbsd_x86_has_futimes 1
#define __openbsd_generic_has_futimes 0
#define __openbsd_x64_has_futimes 0
#define __openbsd_x86_has_futimes 0

/* check SYS_getdents */
#define __darwin_arm64_has_getdents 0
#define __darwin_generic_has_getdents 0
#define __darwin_x64_has_getdents 0
#define __dragonfly_generic_has_getdents 0
#define __dragonfly_x64_has_getdents 0
#define __dragonfly_x86_has_getdents 0
#define __freebsd_generic_has_getdents 1
#define __freebsd_x64_has_getdents 1
#define __freebsd_x86_has_getdents 1
#define __linux_alpha_has_getdents 0
#define __linux_arc_has_getdents 0
#define __linux_arm32_has_getdents 1
#define __linux_arm64_has_getdents 0
#define __linux_csky_has_getdents 0
#define __linux_generic_has_getdents 0
#define __linux_hexagon_has_getdents 0
#define __linux_hppa_has_getdents 1
#define __linux_loongarch64_has_getdents 0
#define __linux_m68k_has_getdents 0
#define __linux_microblaze_has_getdents 0
#define __linux_mips32_has_getdents 1
#define __linux_mips64_has_getdents 1
#define __linux_nios2_has_getdents 0
#define __linux_or1k_has_getdents 0
#define __linux_powerpc32_has_getdents 1
#define __linux_powerpc64_has_getdents 1
#define __linux_riscv32_has_getdents 0
#define __linux_riscv64_has_getdents 0
#define __linux_s390x_has_getdents 1
#define __linux_sh4_has_getdents 1
#define __linux_sparc32_has_getdents 1
#define __linux_sparc64_has_getdents 1
#define __linux_x64_has_getdents 1
#define __linux_x86_has_getdents 1
#define __linux_xtensa_has_getdents 1
#define __netbsd_alpha_has_getdents 1
#define __netbsd_arm32_has_getdents 1
#define __netbsd_arm64_has_getdents 1
#define __netbsd_generic_has_getdents 1
#define __netbsd_hppa_has_getdents 1
#define __netbsd_ia64_has_getdents 1
#define __netbsd_powerpc32_has_getdents 1
#define __netbsd_powerpc64_has_getdents 1
#define __netbsd_riscv32_has_getdents 1
#define __netbsd_riscv64_has_getdents 1
#define __netbsd_sparc32_has_getdents 1
#define __netbsd_sparc64_has_getdents 1
#define __netbsd_vax_has_getdents 1
#define __netbsd_x64_has_getdents 1
#define __netbsd_x86_has_getdents 1
#define __openbsd_generic_has_getdents 1
#define __openbsd_x64_has_getdents 1
#define __openbsd_x86_has_getdents 1

/* check SYS_getdents64 */
#define __darwin_arm64_has_getdents64 0
#define __darwin_generic_has_getdents64 0
#define __darwin_x64_has_getdents64 0
#define __dragonfly_generic_has_getdents64 0
#define __dragonfly_x64_has_getdents64 0
#define __dragonfly_x86_has_getdents64 0
#define __freebsd_generic_has_getdents64 0
#define __freebsd_x64_has_getdents64 0
#define __freebsd_x86_has_getdents64 0
#define __linux_alpha_has_getdents64 1
#define __linux_arc_has_getdents64 1
#define __linux_arm32_has_getdents64 1
#define __linux_arm64_has_getdents64 1
#define __linux_csky_has_getdents64 1
#define __linux_generic_has_getdents64 1
#define __linux_hexagon_has_getdents64 1
#define __linux_hppa_has_getdents64 1
#define __linux_loongarch64_has_getdents64 1
#define __linux_m68k_has_getdents64 1
#define __linux_microblaze_has_getdents64 1
#define __linux_mips32_has_getdents64 1
#define __linux_mips64_has_getdents64 1
#define __linux_nios2_has_getdents64 1
#define __linux_or1k_has_getdents64 1
#define __linux_powerpc32_has_getdents64 1
#define __linux_powerpc64_has_getdents64 1
#define __linux_riscv32_has_getdents64 1
#define __linux_riscv64_has_getdents64 1
#define __linux_s390x_has_getdents64 1
#define __linux_sh4_has_getdents64 1
#define __linux_sparc32_has_getdents64 1
#define __linux_sparc64_has_getdents64 1
#define __linux_x64_has_getdents64 1
#define __linux_x86_has_getdents64 1
#define __linux_xtensa_has_getdents64 1
#define __netbsd_alpha_has_getdents64 0
#define __netbsd_arm32_has_getdents64 0
#define __netbsd_arm64_has_getdents64 0
#define __netbsd_generic_has_getdents64 0
#define __netbsd_hppa_has_getdents64 0
#define __netbsd_ia64_has_getdents64 0
#define __netbsd_powerpc32_has_getdents64 0
#define __netbsd_powerpc64_has_getdents64 0
#define __netbsd_riscv32_has_getdents64 0
#define __netbsd_riscv64_has_getdents64 0
#define __netbsd_sparc32_has_getdents64 0
#define __netbsd_sparc64_has_getdents64 0
#define __netbsd_vax_has_getdents64 0
#define __netbsd_x64_has_getdents64 0
#define __netbsd_x86_has_getdents64 0
#define __openbsd_generic_has_getdents64 0
#define __openbsd_x64_has_getdents64 0
#define __openbsd_x86_has_getdents64 0

/* check SYS_gethostname */
#define __darwin_arm64_has_gethostname 0
#define __darwin_generic_has_gethostname 0
#define __darwin_x64_has_gethostname 0
#define __dragonfly_generic_has_gethostname 0
#define __dragonfly_x64_has_gethostname 0
#define __dragonfly_x86_has_gethostname 0
#define __freebsd_generic_has_gethostname 1
#define __freebsd_x64_has_gethostname 1
#define __freebsd_x86_has_gethostname 1
#define __linux_alpha_has_gethostname 0
#define __linux_arc_has_gethostname 0
#define __linux_arm32_has_gethostname 0
#define __linux_arm64_has_gethostname 0
#define __linux_csky_has_gethostname 0
#define __linux_generic_has_gethostname 0
#define __linux_hexagon_has_gethostname 0
#define __linux_hppa_has_gethostname 0
#define __linux_loongarch64_has_gethostname 0
#define __linux_m68k_has_gethostname 0
#define __linux_microblaze_has_gethostname 0
#define __linux_mips32_has_gethostname 0
#define __linux_mips64_has_gethostname 0
#define __linux_nios2_has_gethostname 0
#define __linux_or1k_has_gethostname 0
#define __linux_powerpc32_has_gethostname 0
#define __linux_powerpc64_has_gethostname 0
#define __linux_riscv32_has_gethostname 0
#define __linux_riscv64_has_gethostname 0
#define __linux_s390x_has_gethostname 0
#define __linux_sh4_has_gethostname 0
#define __linux_sparc32_has_gethostname 0
#define __linux_sparc64_has_gethostname 0
#define __linux_x64_has_gethostname 0
#define __linux_x86_has_gethostname 0
#define __linux_xtensa_has_gethostname 0
#define __netbsd_alpha_has_gethostname 0
#define __netbsd_arm32_has_gethostname 0
#define __netbsd_arm64_has_gethostname 0
#define __netbsd_generic_has_gethostname 0
#define __netbsd_hppa_has_gethostname 0
#define __netbsd_ia64_has_gethostname 0
#define __netbsd_powerpc32_has_gethostname 0
#define __netbsd_powerpc64_has_gethostname 0
#define __netbsd_riscv32_has_gethostname 0
#define __netbsd_riscv64_has_gethostname 0
#define __netbsd_sparc32_has_gethostname 0
#define __netbsd_sparc64_has_gethostname 0
#define __netbsd_vax_has_gethostname 0
#define __netbsd_x64_has_gethostname 0
#define __netbsd_x86_has_gethostname 0
#define __openbsd_generic_has_gethostname 0
#define __openbsd_x64_has_gethostname 0
#define __openbsd_x86_has_gethostname 0

/* check SYS_getitimer */
#define __darwin_arm64_has_getitimer 1
#define __darwin_generic_has_getitimer 1
#define __darwin_x64_has_getitimer 1
#define __dragonfly_generic_has_getitimer 1
#define __dragonfly_x64_has_getitimer 1
#define __dragonfly_x86_has_getitimer 1
#define __freebsd_generic_has_getitimer 1
#define __freebsd_x64_has_getitimer 1
#define __freebsd_x86_has_getitimer 1
#define __linux_alpha_has_getitimer 1
#define __linux_arc_has_getitimer 1
#define __linux_arm32_has_getitimer 1
#define __linux_arm64_has_getitimer 1
#define __linux_csky_has_getitimer 1
#define __linux_generic_has_getitimer 1
#define __linux_hexagon_has_getitimer 1
#define __linux_hppa_has_getitimer 1
#define __linux_loongarch64_has_getitimer 1
#define __linux_m68k_has_getitimer 1
#define __linux_microblaze_has_getitimer 1
#define __linux_mips32_has_getitimer 1
#define __linux_mips64_has_getitimer 1
#define __linux_nios2_has_getitimer 1
#define __linux_or1k_has_getitimer 1
#define __linux_powerpc32_has_getitimer 1
#define __linux_powerpc64_has_getitimer 1
#define __linux_riscv32_has_getitimer 1
#define __linux_riscv64_has_getitimer 1
#define __linux_s390x_has_getitimer 1
#define __linux_sh4_has_getitimer 1
#define __linux_sparc32_has_getitimer 1
#define __linux_sparc64_has_getitimer 1
#define __linux_x64_has_getitimer 1
#define __linux_x86_has_getitimer 1
#define __linux_xtensa_has_getitimer 1
#define __netbsd_alpha_has_getitimer 1
#define __netbsd_arm32_has_getitimer 1
#define __netbsd_arm64_has_getitimer 1
#define __netbsd_generic_has_getitimer 1
#define __netbsd_hppa_has_getitimer 1
#define __netbsd_ia64_has_getitimer 1
#define __netbsd_powerpc32_has_getitimer 1
#define __netbsd_powerpc64_has_getitimer 1
#define __netbsd_riscv32_has_getitimer 1
#define __netbsd_riscv64_has_getitimer 1
#define __netbsd_sparc32_has_getitimer 1
#define __netbsd_sparc64_has_getitimer 1
#define __netbsd_vax_has_getitimer 1
#define __netbsd_x64_has_getitimer 1
#define __netbsd_x86_has_getitimer 1
#define __openbsd_generic_has_getitimer 0
#define __openbsd_x64_has_getitimer 0
#define __openbsd_x86_has_getitimer 0

/* check SYS_gettimeofday */
#define __darwin_arm64_has_gettimeofday 0
#define __darwin_generic_has_gettimeofday 0
#define __darwin_x64_has_gettimeofday 0
#define __dragonfly_generic_has_gettimeofday 1
#define __dragonfly_x64_has_gettimeofday 1
#define __dragonfly_x86_has_gettimeofday 1
#define __freebsd_generic_has_gettimeofday 1
#define __freebsd_x64_has_gettimeofday 1
#define __freebsd_x86_has_gettimeofday 1
#define __linux_alpha_has_gettimeofday 1
#define __linux_arc_has_gettimeofday 1
#define __linux_arm32_has_gettimeofday 1
#define __linux_arm64_has_gettimeofday 1
#define __linux_csky_has_gettimeofday 1
#define __linux_generic_has_gettimeofday 1
#define __linux_hexagon_has_gettimeofday 1
#define __linux_hppa_has_gettimeofday 1
#define __linux_loongarch64_has_gettimeofday 1
#define __linux_m68k_has_gettimeofday 1
#define __linux_microblaze_has_gettimeofday 1
#define __linux_mips32_has_gettimeofday 1
#define __linux_mips64_has_gettimeofday 1
#define __linux_nios2_has_gettimeofday 1
#define __linux_or1k_has_gettimeofday 1
#define __linux_powerpc32_has_gettimeofday 1
#define __linux_powerpc64_has_gettimeofday 1
#define __linux_riscv32_has_gettimeofday 1
#define __linux_riscv64_has_gettimeofday 1
#define __linux_s390x_has_gettimeofday 1
#define __linux_sh4_has_gettimeofday 1
#define __linux_sparc32_has_gettimeofday 1
#define __linux_sparc64_has_gettimeofday 1
#define __linux_x64_has_gettimeofday 1
#define __linux_x86_has_gettimeofday 1
#define __linux_xtensa_has_gettimeofday 1
#define __netbsd_alpha_has_gettimeofday 1
#define __netbsd_arm32_has_gettimeofday 1
#define __netbsd_arm64_has_gettimeofday 1
#define __netbsd_generic_has_gettimeofday 1
#define __netbsd_hppa_has_gettimeofday 1
#define __netbsd_ia64_has_gettimeofday 1
#define __netbsd_powerpc32_has_gettimeofday 1
#define __netbsd_powerpc64_has_gettimeofday 1
#define __netbsd_riscv32_has_gettimeofday 1
#define __netbsd_riscv64_has_gettimeofday 1
#define __netbsd_sparc32_has_gettimeofday 1
#define __netbsd_sparc64_has_gettimeofday 1
#define __netbsd_vax_has_gettimeofday 1
#define __netbsd_x64_has_gettimeofday 1
#define __netbsd_x86_has_gettimeofday 1
#define __openbsd_generic_has_gettimeofday 0
#define __openbsd_x64_has_gettimeofday 0
#define __openbsd_x86_has_gettimeofday 0

/* check SYS_ioctl */
#define __darwin_arm64_has_ioctl 0
#define __darwin_generic_has_ioctl 0
#define __darwin_x64_has_ioctl 0
#define __dragonfly_generic_has_ioctl 1
#define __dragonfly_x64_has_ioctl 1
#define __dragonfly_x86_has_ioctl 1
#define __freebsd_generic_has_ioctl 1
#define __freebsd_x64_has_ioctl 1
#define __freebsd_x86_has_ioctl 1
#define __linux_alpha_has_ioctl 1
#define __linux_arc_has_ioctl 1
#define __linux_arm32_has_ioctl 1
#define __linux_arm64_has_ioctl 1
#define __linux_csky_has_ioctl 1
#define __linux_generic_has_ioctl 1
#define __linux_hexagon_has_ioctl 1
#define __linux_hppa_has_ioctl 1
#define __linux_loongarch64_has_ioctl 1
#define __linux_m68k_has_ioctl 1
#define __linux_microblaze_has_ioctl 1
#define __linux_mips32_has_ioctl 1
#define __linux_mips64_has_ioctl 1
#define __linux_nios2_has_ioctl 1
#define __linux_or1k_has_ioctl 1
#define __linux_powerpc32_has_ioctl 1
#define __linux_powerpc64_has_ioctl 1
#define __linux_riscv32_has_ioctl 1
#define __linux_riscv64_has_ioctl 1
#define __linux_s390x_has_ioctl 1
#define __linux_sh4_has_ioctl 1
#define __linux_sparc32_has_ioctl 1
#define __linux_sparc64_has_ioctl 1
#define __linux_x64_has_ioctl 1
#define __linux_x86_has_ioctl 1
#define __linux_xtensa_has_ioctl 1
#define __netbsd_alpha_has_ioctl 1
#define __netbsd_arm32_has_ioctl 1
#define __netbsd_arm64_has_ioctl 1
#define __netbsd_generic_has_ioctl 1
#define __netbsd_hppa_has_ioctl 1
#define __netbsd_ia64_has_ioctl 1
#define __netbsd_powerpc32_has_ioctl 1
#define __netbsd_powerpc64_has_ioctl 1
#define __netbsd_riscv32_has_ioctl 1
#define __netbsd_riscv64_has_ioctl 1
#define __netbsd_sparc32_has_ioctl 1
#define __netbsd_sparc64_has_ioctl 1
#define __netbsd_vax_has_ioctl 1
#define __netbsd_x64_has_ioctl 1
#define __netbsd_x86_has_ioctl 1
#define __openbsd_generic_has_ioctl 0
#define __openbsd_x64_has_ioctl 0
#define __openbsd_x86_has_ioctl 0

/* check SYS_lstat */
#define __darwin_arm64_has_lstat 0
#define __darwin_generic_has_lstat 0
#define __darwin_x64_has_lstat 0
#define __dragonfly_generic_has_lstat 1
#define __dragonfly_x64_has_lstat 1
#define __dragonfly_x86_has_lstat 1
#define __freebsd_generic_has_lstat 1
#define __freebsd_x64_has_lstat 1
#define __freebsd_x86_has_lstat 1
#define __linux_alpha_has_lstat 0
#define __linux_arc_has_lstat 0
#define __linux_arm32_has_lstat 1
#define __linux_arm64_has_lstat 0
#define __linux_csky_has_lstat 0
#define __linux_generic_has_lstat 0
#define __linux_hexagon_has_lstat 0
#define __linux_hppa_has_lstat 1
#define __linux_loongarch64_has_lstat 0
#define __linux_m68k_has_lstat 0
#define __linux_microblaze_has_lstat 0
#define __linux_mips32_has_lstat 1
#define __linux_mips64_has_lstat 1
#define __linux_nios2_has_lstat 0
#define __linux_or1k_has_lstat 0
#define __linux_powerpc32_has_lstat 1
#define __linux_powerpc64_has_lstat 1
#define __linux_riscv32_has_lstat 0
#define __linux_riscv64_has_lstat 0
#define __linux_s390x_has_lstat 1
#define __linux_sh4_has_lstat 1
#define __linux_sparc32_has_lstat 1
#define __linux_sparc64_has_lstat 1
#define __linux_x64_has_lstat 1
#define __linux_x86_has_lstat 1
#define __linux_xtensa_has_lstat 1
#define __netbsd_alpha_has_lstat 0
#define __netbsd_arm32_has_lstat 0
#define __netbsd_arm64_has_lstat 0
#define __netbsd_generic_has_lstat 0
#define __netbsd_hppa_has_lstat 0
#define __netbsd_ia64_has_lstat 0
#define __netbsd_powerpc32_has_lstat 0
#define __netbsd_powerpc64_has_lstat 0
#define __netbsd_riscv32_has_lstat 0
#define __netbsd_riscv64_has_lstat 0
#define __netbsd_sparc32_has_lstat 0
#define __netbsd_sparc64_has_lstat 0
#define __netbsd_vax_has_lstat 0
#define __netbsd_x64_has_lstat 0
#define __netbsd_x86_has_lstat 0
#define __openbsd_generic_has_lstat 1
#define __openbsd_x64_has_lstat 1
#define __openbsd_x86_has_lstat 1

/* check SYS_lstat64 */
#define __darwin_arm64_has_lstat64 1
#define __darwin_generic_has_lstat64 1
#define __darwin_x64_has_lstat64 1
#define __dragonfly_generic_has_lstat64 0
#define __dragonfly_x64_has_lstat64 0
#define __dragonfly_x86_has_lstat64 0
#define __freebsd_generic_has_lstat64 0
#define __freebsd_x64_has_lstat64 0
#define __freebsd_x86_has_lstat64 0
#define __linux_alpha_has_lstat64 0
#define __linux_arc_has_lstat64 0
#define __linux_arm32_has_lstat64 1
#define __linux_arm64_has_lstat64 0
#define __linux_csky_has_lstat64 0
#define __linux_generic_has_lstat64 0
#define __linux_hexagon_has_lstat64 0
#define __linux_hppa_has_lstat64 1
#define __linux_loongarch64_has_lstat64 0
#define __linux_m68k_has_lstat64 0
#define __linux_microblaze_has_lstat64 0
#define __linux_mips32_has_lstat64 0
#define __linux_mips64_has_lstat64 0
#define __linux_nios2_has_lstat64 0
#define __linux_or1k_has_lstat64 0
#define __linux_powerpc32_has_lstat64 1
#define __linux_powerpc64_has_lstat64 1
#define __linux_riscv32_has_lstat64 0
#define __linux_riscv64_has_lstat64 0
#define __linux_s390x_has_lstat64 1
#define __linux_sh4_has_lstat64 1
#define __linux_sparc32_has_lstat64 1
#define __linux_sparc64_has_lstat64 1
#define __linux_x64_has_lstat64 0
#define __linux_x86_has_lstat64 1
#define __linux_xtensa_has_lstat64 1
#define __netbsd_alpha_has_lstat64 0
#define __netbsd_arm32_has_lstat64 0
#define __netbsd_arm64_has_lstat64 0
#define __netbsd_generic_has_lstat64 0
#define __netbsd_hppa_has_lstat64 0
#define __netbsd_ia64_has_lstat64 0
#define __netbsd_powerpc32_has_lstat64 0
#define __netbsd_powerpc64_has_lstat64 0
#define __netbsd_riscv32_has_lstat64 0
#define __netbsd_riscv64_has_lstat64 0
#define __netbsd_sparc32_has_lstat64 0
#define __netbsd_sparc64_has_lstat64 0
#define __netbsd_vax_has_lstat64 0
#define __netbsd_x64_has_lstat64 0
#define __netbsd_x86_has_lstat64 0
#define __openbsd_generic_has_lstat64 0
#define __openbsd_x64_has_lstat64 0
#define __openbsd_x86_has_lstat64 0

/* check SYS_lutimes */
#define __darwin_arm64_has_lutimes 0
#define __darwin_generic_has_lutimes 0
#define __darwin_x64_has_lutimes 0
#define __dragonfly_generic_has_lutimes 1
#define __dragonfly_x64_has_lutimes 1
#define __dragonfly_x86_has_lutimes 1
#define __freebsd_generic_has_lutimes 1
#define __freebsd_x64_has_lutimes 1
#define __freebsd_x86_has_lutimes 1
#define __linux_alpha_has_lutimes 0
#define __linux_arc_has_lutimes 0
#define __linux_arm32_has_lutimes 0
#define __linux_arm64_has_lutimes 0
#define __linux_csky_has_lutimes 0
#define __linux_generic_has_lutimes 0
#define __linux_hexagon_has_lutimes 0
#define __linux_hppa_has_lutimes 0
#define __linux_loongarch64_has_lutimes 0
#define __linux_m68k_has_lutimes 0
#define __linux_microblaze_has_lutimes 0
#define __linux_mips32_has_lutimes 0
#define __linux_mips64_has_lutimes 0
#define __linux_nios2_has_lutimes 0
#define __linux_or1k_has_lutimes 0
#define __linux_powerpc32_has_lutimes 0
#define __linux_powerpc64_has_lutimes 0
#define __linux_riscv32_has_lutimes 0
#define __linux_riscv64_has_lutimes 0
#define __linux_s390x_has_lutimes 0
#define __linux_sh4_has_lutimes 0
#define __linux_sparc32_has_lutimes 0
#define __linux_sparc64_has_lutimes 0
#define __linux_x64_has_lutimes 0
#define __linux_x86_has_lutimes 0
#define __linux_xtensa_has_lutimes 0
#define __netbsd_alpha_has_lutimes 1
#define __netbsd_arm32_has_lutimes 1
#define __netbsd_arm64_has_lutimes 1
#define __netbsd_generic_has_lutimes 1
#define __netbsd_hppa_has_lutimes 1
#define __netbsd_ia64_has_lutimes 1
#define __netbsd_powerpc32_has_lutimes 1
#define __netbsd_powerpc64_has_lutimes 1
#define __netbsd_riscv32_has_lutimes 1
#define __netbsd_riscv64_has_lutimes 1
#define __netbsd_sparc32_has_lutimes 1
#define __netbsd_sparc64_has_lutimes 1
#define __netbsd_vax_has_lutimes 1
#define __netbsd_x64_has_lutimes 1
#define __netbsd_x86_has_lutimes 1
#define __openbsd_generic_has_lutimes 0
#define __openbsd_x64_has_lutimes 0
#define __openbsd_x86_has_lutimes 0

/* check SYS_mkdir */
#define __darwin_arm64_has_mkdir 0
#define __darwin_generic_has_mkdir 0
#define __darwin_x64_has_mkdir 0
#define __dragonfly_generic_has_mkdir 0
#define __dragonfly_x64_has_mkdir 0
#define __dragonfly_x86_has_mkdir 0
#define __freebsd_generic_has_mkdir 1
#define __freebsd_x64_has_mkdir 1
#define __freebsd_x86_has_mkdir 1
#define __linux_alpha_has_mkdir 0
#define __linux_arc_has_mkdir 0
#define __linux_arm32_has_mkdir 1
#define __linux_arm64_has_mkdir 0
#define __linux_csky_has_mkdir 0
#define __linux_generic_has_mkdir 0
#define __linux_hexagon_has_mkdir 0
#define __linux_hppa_has_mkdir 1
#define __linux_loongarch64_has_mkdir 0
#define __linux_m68k_has_mkdir 0
#define __linux_microblaze_has_mkdir 0
#define __linux_mips32_has_mkdir 1
#define __linux_mips64_has_mkdir 1
#define __linux_nios2_has_mkdir 0
#define __linux_or1k_has_mkdir 0
#define __linux_powerpc32_has_mkdir 1
#define __linux_powerpc64_has_mkdir 1
#define __linux_riscv32_has_mkdir 0
#define __linux_riscv64_has_mkdir 0
#define __linux_s390x_has_mkdir 1
#define __linux_sh4_has_mkdir 1
#define __linux_sparc32_has_mkdir 1
#define __linux_sparc64_has_mkdir 1
#define __linux_x64_has_mkdir 1
#define __linux_x86_has_mkdir 1
#define __linux_xtensa_has_mkdir 1
#define __netbsd_alpha_has_mkdir 0
#define __netbsd_arm32_has_mkdir 0
#define __netbsd_arm64_has_mkdir 0
#define __netbsd_generic_has_mkdir 0
#define __netbsd_hppa_has_mkdir 0
#define __netbsd_ia64_has_mkdir 0
#define __netbsd_powerpc32_has_mkdir 0
#define __netbsd_powerpc64_has_mkdir 0
#define __netbsd_riscv32_has_mkdir 0
#define __netbsd_riscv64_has_mkdir 0
#define __netbsd_sparc32_has_mkdir 0
#define __netbsd_sparc64_has_mkdir 0
#define __netbsd_vax_has_mkdir 0
#define __netbsd_x64_has_mkdir 0
#define __netbsd_x86_has_mkdir 0
#define __openbsd_generic_has_mkdir 1
#define __openbsd_x64_has_mkdir 1
#define __openbsd_x86_has_mkdir 1

/* check SYS_mkdirat */
#define __darwin_arm64_has_mkdirat 1
#define __darwin_generic_has_mkdirat 1
#define __darwin_x64_has_mkdirat 1
#define __dragonfly_generic_has_mkdirat 0
#define __dragonfly_x64_has_mkdirat 0
#define __dragonfly_x86_has_mkdirat 0
#define __freebsd_generic_has_mkdirat 1
#define __freebsd_x64_has_mkdirat 1
#define __freebsd_x86_has_mkdirat 1
#define __linux_alpha_has_mkdirat 1
#define __linux_arc_has_mkdirat 1
#define __linux_arm32_has_mkdirat 1
#define __linux_arm64_has_mkdirat 1
#define __linux_csky_has_mkdirat 1
#define __linux_generic_has_mkdirat 1
#define __linux_hexagon_has_mkdirat 1
#define __linux_hppa_has_mkdirat 1
#define __linux_loongarch64_has_mkdirat 1
#define __linux_m68k_has_mkdirat 1
#define __linux_microblaze_has_mkdirat 1
#define __linux_mips32_has_mkdirat 1
#define __linux_mips64_has_mkdirat 1
#define __linux_nios2_has_mkdirat 1
#define __linux_or1k_has_mkdirat 1
#define __linux_powerpc32_has_mkdirat 1
#define __linux_powerpc64_has_mkdirat 1
#define __linux_riscv32_has_mkdirat 1
#define __linux_riscv64_has_mkdirat 1
#define __linux_s390x_has_mkdirat 1
#define __linux_sh4_has_mkdirat 1
#define __linux_sparc32_has_mkdirat 1
#define __linux_sparc64_has_mkdirat 1
#define __linux_x64_has_mkdirat 1
#define __linux_x86_has_mkdirat 1
#define __linux_xtensa_has_mkdirat 1
#define __netbsd_alpha_has_mkdirat 1
#define __netbsd_arm32_has_mkdirat 1
#define __netbsd_arm64_has_mkdirat 1
#define __netbsd_generic_has_mkdirat 1
#define __netbsd_hppa_has_mkdirat 1
#define __netbsd_ia64_has_mkdirat 1
#define __netbsd_powerpc32_has_mkdirat 1
#define __netbsd_powerpc64_has_mkdirat 1
#define __netbsd_riscv32_has_mkdirat 1
#define __netbsd_riscv64_has_mkdirat 1
#define __netbsd_sparc32_has_mkdirat 1
#define __netbsd_sparc64_has_mkdirat 1
#define __netbsd_vax_has_mkdirat 1
#define __netbsd_x64_has_mkdirat 1
#define __netbsd_x86_has_mkdirat 1
#define __openbsd_generic_has_mkdirat 0
#define __openbsd_x64_has_mkdirat 0
#define __openbsd_x86_has_mkdirat 0

/* check SYS_nanosleep */
#define __darwin_arm64_has_nanosleep 0
#define __darwin_generic_has_nanosleep 0
#define __darwin_x64_has_nanosleep 0
#define __dragonfly_generic_has_nanosleep 1
#define __dragonfly_x64_has_nanosleep 1
#define __dragonfly_x86_has_nanosleep 1
#define __freebsd_generic_has_nanosleep 1
#define __freebsd_x64_has_nanosleep 1
#define __freebsd_x86_has_nanosleep 1
#define __linux_alpha_has_nanosleep 1
#define __linux_arc_has_nanosleep 1
#define __linux_arm32_has_nanosleep 1
#define __linux_arm64_has_nanosleep 1
#define __linux_csky_has_nanosleep 1
#define __linux_generic_has_nanosleep 1
#define __linux_hexagon_has_nanosleep 1
#define __linux_hppa_has_nanosleep 1
#define __linux_loongarch64_has_nanosleep 1
#define __linux_m68k_has_nanosleep 1
#define __linux_microblaze_has_nanosleep 1
#define __linux_mips32_has_nanosleep 1
#define __linux_mips64_has_nanosleep 1
#define __linux_nios2_has_nanosleep 1
#define __linux_or1k_has_nanosleep 1
#define __linux_powerpc32_has_nanosleep 1
#define __linux_powerpc64_has_nanosleep 1
#define __linux_riscv32_has_nanosleep 1
#define __linux_riscv64_has_nanosleep 1
#define __linux_s390x_has_nanosleep 1
#define __linux_sh4_has_nanosleep 1
#define __linux_sparc32_has_nanosleep 1
#define __linux_sparc64_has_nanosleep 1
#define __linux_x64_has_nanosleep 1
#define __linux_x86_has_nanosleep 1
#define __linux_xtensa_has_nanosleep 1
#define __netbsd_alpha_has_nanosleep 1
#define __netbsd_arm32_has_nanosleep 1
#define __netbsd_arm64_has_nanosleep 1
#define __netbsd_generic_has_nanosleep 1
#define __netbsd_hppa_has_nanosleep 1
#define __netbsd_ia64_has_nanosleep 1
#define __netbsd_powerpc32_has_nanosleep 1
#define __netbsd_powerpc64_has_nanosleep 1
#define __netbsd_riscv32_has_nanosleep 1
#define __netbsd_riscv64_has_nanosleep 1
#define __netbsd_sparc32_has_nanosleep 1
#define __netbsd_sparc64_has_nanosleep 1
#define __netbsd_vax_has_nanosleep 1
#define __netbsd_x64_has_nanosleep 1
#define __netbsd_x86_has_nanosleep 1
#define __openbsd_generic_has_nanosleep 0
#define __openbsd_x64_has_nanosleep 0
#define __openbsd_x86_has_nanosleep 0

/* check SYS_newfstatat */
#define __darwin_arm64_has_newfstatat 0
#define __darwin_generic_has_newfstatat 0
#define __darwin_x64_has_newfstatat 0
#define __dragonfly_generic_has_newfstatat 0
#define __dragonfly_x64_has_newfstatat 0
#define __dragonfly_x86_has_newfstatat 0
#define __freebsd_generic_has_newfstatat 0
#define __freebsd_x64_has_newfstatat 0
#define __freebsd_x86_has_newfstatat 0
#define __linux_alpha_has_newfstatat 1
#define __linux_arc_has_newfstatat 1
#define __linux_arm32_has_newfstatat 0
#define __linux_arm64_has_newfstatat 1
#define __linux_csky_has_newfstatat 1
#define __linux_generic_has_newfstatat 1
#define __linux_hexagon_has_newfstatat 1
#define __linux_hppa_has_newfstatat 0
#define __linux_loongarch64_has_newfstatat 1
#define __linux_m68k_has_newfstatat 1
#define __linux_microblaze_has_newfstatat 1
#define __linux_mips32_has_newfstatat 1
#define __linux_mips64_has_newfstatat 1
#define __linux_nios2_has_newfstatat 1
#define __linux_or1k_has_newfstatat 1
#define __linux_powerpc32_has_newfstatat 1
#define __linux_powerpc64_has_newfstatat 1
#define __linux_riscv32_has_newfstatat 1
#define __linux_riscv64_has_newfstatat 1
#define __linux_s390x_has_newfstatat 1
#define __linux_sh4_has_newfstatat 0
#define __linux_sparc32_has_newfstatat 0
#define __linux_sparc64_has_newfstatat 0
#define __linux_x64_has_newfstatat 1
#define __linux_x86_has_newfstatat 0
#define __linux_xtensa_has_newfstatat 0
#define __netbsd_alpha_has_newfstatat 0
#define __netbsd_arm32_has_newfstatat 0
#define __netbsd_arm64_has_newfstatat 0
#define __netbsd_generic_has_newfstatat 0
#define __netbsd_hppa_has_newfstatat 0
#define __netbsd_ia64_has_newfstatat 0
#define __netbsd_powerpc32_has_newfstatat 0
#define __netbsd_powerpc64_has_newfstatat 0
#define __netbsd_riscv32_has_newfstatat 0
#define __netbsd_riscv64_has_newfstatat 0
#define __netbsd_sparc32_has_newfstatat 0
#define __netbsd_sparc64_has_newfstatat 0
#define __netbsd_vax_has_newfstatat 0
#define __netbsd_x64_has_newfstatat 0
#define __netbsd_x86_has_newfstatat 0
#define __openbsd_generic_has_newfstatat 0
#define __openbsd_x64_has_newfstatat 0
#define __openbsd_x86_has_newfstatat 0

/* check SYS_open */
#define __darwin_arm64_has_open 1
#define __darwin_generic_has_open 1
#define __darwin_x64_has_open 1
#define __dragonfly_generic_has_open 1
#define __dragonfly_x64_has_open 1
#define __dragonfly_x86_has_open 1
#define __freebsd_generic_has_open 1
#define __freebsd_x64_has_open 1
#define __freebsd_x86_has_open 1
#define __linux_alpha_has_open 0
#define __linux_arc_has_open 0
#define __linux_arm32_has_open 1
#define __linux_arm64_has_open 0
#define __linux_csky_has_open 0
#define __linux_generic_has_open 0
#define __linux_hexagon_has_open 0
#define __linux_hppa_has_open 1
#define __linux_loongarch64_has_open 0
#define __linux_m68k_has_open 0
#define __linux_microblaze_has_open 0
#define __linux_mips32_has_open 1
#define __linux_mips64_has_open 1
#define __linux_nios2_has_open 0
#define __linux_or1k_has_open 0
#define __linux_powerpc32_has_open 1
#define __linux_powerpc64_has_open 1
#define __linux_riscv32_has_open 0
#define __linux_riscv64_has_open 0
#define __linux_s390x_has_open 1
#define __linux_sh4_has_open 1
#define __linux_sparc32_has_open 1
#define __linux_sparc64_has_open 1
#define __linux_x64_has_open 1
#define __linux_x86_has_open 1
#define __linux_xtensa_has_open 1
#define __netbsd_alpha_has_open 1
#define __netbsd_arm32_has_open 1
#define __netbsd_arm64_has_open 1
#define __netbsd_generic_has_open 1
#define __netbsd_hppa_has_open 1
#define __netbsd_ia64_has_open 1
#define __netbsd_powerpc32_has_open 1
#define __netbsd_powerpc64_has_open 1
#define __netbsd_riscv32_has_open 1
#define __netbsd_riscv64_has_open 1
#define __netbsd_sparc32_has_open 1
#define __netbsd_sparc64_has_open 1
#define __netbsd_vax_has_open 1
#define __netbsd_x64_has_open 1
#define __netbsd_x86_has_open 1
#define __openbsd_generic_has_open 0
#define __openbsd_x64_has_open 0
#define __openbsd_x86_has_open 0

/* check SYS_openat */
#define __darwin_arm64_has_openat 1
#define __darwin_generic_has_openat 1
#define __darwin_x64_has_openat 1
#define __dragonfly_generic_has_openat 1
#define __dragonfly_x64_has_openat 1
#define __dragonfly_x86_has_openat 1
#define __freebsd_generic_has_openat 1
#define __freebsd_x64_has_openat 1
#define __freebsd_x86_has_openat 1
#define __linux_alpha_has_openat 1
#define __linux_arc_has_openat 1
#define __linux_arm32_has_openat 1
#define __linux_arm64_has_openat 1
#define __linux_csky_has_openat 1
#define __linux_generic_has_openat 1
#define __linux_hexagon_has_openat 1
#define __linux_hppa_has_openat 1
#define __linux_loongarch64_has_openat 1
#define __linux_m68k_has_openat 1
#define __linux_microblaze_has_openat 1
#define __linux_mips32_has_openat 1
#define __linux_mips64_has_openat 1
#define __linux_nios2_has_openat 1
#define __linux_or1k_has_openat 1
#define __linux_powerpc32_has_openat 1
#define __linux_powerpc64_has_openat 1
#define __linux_riscv32_has_openat 1
#define __linux_riscv64_has_openat 1
#define __linux_s390x_has_openat 1
#define __linux_sh4_has_openat 1
#define __linux_sparc32_has_openat 1
#define __linux_sparc64_has_openat 1
#define __linux_x64_has_openat 1
#define __linux_x86_has_openat 1
#define __linux_xtensa_has_openat 1
#define __netbsd_alpha_has_openat 1
#define __netbsd_arm32_has_openat 1
#define __netbsd_arm64_has_openat 1
#define __netbsd_generic_has_openat 1
#define __netbsd_hppa_has_openat 1
#define __netbsd_ia64_has_openat 1
#define __netbsd_powerpc32_has_openat 1
#define __netbsd_powerpc64_has_openat 1
#define __netbsd_riscv32_has_openat 1
#define __netbsd_riscv64_has_openat 1
#define __netbsd_sparc32_has_openat 1
#define __netbsd_sparc64_has_openat 1
#define __netbsd_vax_has_openat 1
#define __netbsd_x64_has_openat 1
#define __netbsd_x86_has_openat 1
#define __openbsd_generic_has_openat 0
#define __openbsd_x64_has_openat 0
#define __openbsd_x86_has_openat 0

/* check SYS_pause */
#define __darwin_arm64_has_pause 0
#define __darwin_generic_has_pause 0
#define __darwin_x64_has_pause 0
#define __dragonfly_generic_has_pause 0
#define __dragonfly_x64_has_pause 0
#define __dragonfly_x86_has_pause 0
#define __freebsd_generic_has_pause 0
#define __freebsd_x64_has_pause 0
#define __freebsd_x86_has_pause 0
#define __linux_alpha_has_pause 0
#define __linux_arc_has_pause 0
#define __linux_arm32_has_pause 1
#define __linux_arm64_has_pause 0
#define __linux_csky_has_pause 0
#define __linux_generic_has_pause 0
#define __linux_hexagon_has_pause 0
#define __linux_hppa_has_pause 1
#define __linux_loongarch64_has_pause 0
#define __linux_m68k_has_pause 0
#define __linux_microblaze_has_pause 0
#define __linux_mips32_has_pause 1
#define __linux_mips64_has_pause 1
#define __linux_nios2_has_pause 0
#define __linux_or1k_has_pause 0
#define __linux_powerpc32_has_pause 1
#define __linux_powerpc64_has_pause 1
#define __linux_riscv32_has_pause 0
#define __linux_riscv64_has_pause 0
#define __linux_s390x_has_pause 1
#define __linux_sh4_has_pause 1
#define __linux_sparc32_has_pause 1
#define __linux_sparc64_has_pause 1
#define __linux_x64_has_pause 1
#define __linux_x86_has_pause 1
#define __linux_xtensa_has_pause 0
#define __netbsd_alpha_has_pause 0
#define __netbsd_arm32_has_pause 0
#define __netbsd_arm64_has_pause 0
#define __netbsd_generic_has_pause 0
#define __netbsd_hppa_has_pause 0
#define __netbsd_ia64_has_pause 0
#define __netbsd_powerpc32_has_pause 0
#define __netbsd_powerpc64_has_pause 0
#define __netbsd_riscv32_has_pause 0
#define __netbsd_riscv64_has_pause 0
#define __netbsd_sparc32_has_pause 0
#define __netbsd_sparc64_has_pause 0
#define __netbsd_vax_has_pause 0
#define __netbsd_x64_has_pause 0
#define __netbsd_x86_has_pause 0
#define __openbsd_generic_has_pause 0
#define __openbsd_x64_has_pause 0
#define __openbsd_x86_has_pause 0

/* check SYS_pipe */
#define __darwin_arm64_has_pipe 0
#define __darwin_generic_has_pipe 0
#define __darwin_x64_has_pipe 0
#define __dragonfly_generic_has_pipe 0
#define __dragonfly_x64_has_pipe 0
#define __dragonfly_x86_has_pipe 0
#define __freebsd_generic_has_pipe 1
#define __freebsd_x64_has_pipe 1
#define __freebsd_x86_has_pipe 1
#define __linux_alpha_has_pipe 0
#define __linux_arc_has_pipe 0
#define __linux_arm32_has_pipe 1
#define __linux_arm64_has_pipe 0
#define __linux_csky_has_pipe 0
#define __linux_generic_has_pipe 0
#define __linux_hexagon_has_pipe 0
#define __linux_hppa_has_pipe 1
#define __linux_loongarch64_has_pipe 0
#define __linux_m68k_has_pipe 0
#define __linux_microblaze_has_pipe 0
#define __linux_mips32_has_pipe 1
#define __linux_mips64_has_pipe 1
#define __linux_nios2_has_pipe 0
#define __linux_or1k_has_pipe 0
#define __linux_powerpc32_has_pipe 1
#define __linux_powerpc64_has_pipe 1
#define __linux_riscv32_has_pipe 0
#define __linux_riscv64_has_pipe 0
#define __linux_s390x_has_pipe 1
#define __linux_sh4_has_pipe 1
#define __linux_sparc32_has_pipe 1
#define __linux_sparc64_has_pipe 1
#define __linux_x64_has_pipe 1
#define __linux_x86_has_pipe 1
#define __linux_xtensa_has_pipe 1
#define __netbsd_alpha_has_pipe 1
#define __netbsd_arm32_has_pipe 1
#define __netbsd_arm64_has_pipe 1
#define __netbsd_generic_has_pipe 1
#define __netbsd_hppa_has_pipe 1
#define __netbsd_ia64_has_pipe 1
#define __netbsd_powerpc32_has_pipe 1
#define __netbsd_powerpc64_has_pipe 1
#define __netbsd_riscv32_has_pipe 1
#define __netbsd_riscv64_has_pipe 1
#define __netbsd_sparc32_has_pipe 1
#define __netbsd_sparc64_has_pipe 1
#define __netbsd_vax_has_pipe 1
#define __netbsd_x64_has_pipe 1
#define __netbsd_x86_has_pipe 1
#define __openbsd_generic_has_pipe 1
#define __openbsd_x64_has_pipe 1
#define __openbsd_x86_has_pipe 1

/* check SYS_pipe2 */
#define __darwin_arm64_has_pipe2 0
#define __darwin_generic_has_pipe2 0
#define __darwin_x64_has_pipe2 0
#define __dragonfly_generic_has_pipe2 0
#define __dragonfly_x64_has_pipe2 0
#define __dragonfly_x86_has_pipe2 0
#define __freebsd_generic_has_pipe2 1
#define __freebsd_x64_has_pipe2 1
#define __freebsd_x86_has_pipe2 1
#define __linux_alpha_has_pipe2 1
#define __linux_arc_has_pipe2 1
#define __linux_arm32_has_pipe2 1
#define __linux_arm64_has_pipe2 1
#define __linux_csky_has_pipe2 1
#define __linux_generic_has_pipe2 1
#define __linux_hexagon_has_pipe2 1
#define __linux_hppa_has_pipe2 1
#define __linux_loongarch64_has_pipe2 1
#define __linux_m68k_has_pipe2 1
#define __linux_microblaze_has_pipe2 1
#define __linux_mips32_has_pipe2 1
#define __linux_mips64_has_pipe2 1
#define __linux_nios2_has_pipe2 1
#define __linux_or1k_has_pipe2 1
#define __linux_powerpc32_has_pipe2 1
#define __linux_powerpc64_has_pipe2 1
#define __linux_riscv32_has_pipe2 1
#define __linux_riscv64_has_pipe2 1
#define __linux_s390x_has_pipe2 1
#define __linux_sh4_has_pipe2 1
#define __linux_sparc32_has_pipe2 1
#define __linux_sparc64_has_pipe2 1
#define __linux_x64_has_pipe2 1
#define __linux_x86_has_pipe2 1
#define __linux_xtensa_has_pipe2 1
#define __netbsd_alpha_has_pipe2 0
#define __netbsd_arm32_has_pipe2 0
#define __netbsd_arm64_has_pipe2 0
#define __netbsd_generic_has_pipe2 0
#define __netbsd_hppa_has_pipe2 0
#define __netbsd_ia64_has_pipe2 0
#define __netbsd_powerpc32_has_pipe2 0
#define __netbsd_powerpc64_has_pipe2 0
#define __netbsd_riscv32_has_pipe2 0
#define __netbsd_riscv64_has_pipe2 0
#define __netbsd_sparc32_has_pipe2 0
#define __netbsd_sparc64_has_pipe2 0
#define __netbsd_vax_has_pipe2 0
#define __netbsd_x64_has_pipe2 0
#define __netbsd_x86_has_pipe2 0
#define __openbsd_generic_has_pipe2 1
#define __openbsd_x64_has_pipe2 1
#define __openbsd_x86_has_pipe2 1

/* check SYS_sethostname */
#define __darwin_arm64_has_sethostname 0
#define __darwin_generic_has_sethostname 0
#define __darwin_x64_has_sethostname 0
#define __dragonfly_generic_has_sethostname 0
#define __dragonfly_x64_has_sethostname 0
#define __dragonfly_x86_has_sethostname 0
#define __freebsd_generic_has_sethostname 1
#define __freebsd_x64_has_sethostname 1
#define __freebsd_x86_has_sethostname 1
#define __linux_alpha_has_sethostname 1
#define __linux_arc_has_sethostname 1
#define __linux_arm32_has_sethostname 1
#define __linux_arm64_has_sethostname 1
#define __linux_csky_has_sethostname 1
#define __linux_generic_has_sethostname 1
#define __linux_hexagon_has_sethostname 1
#define __linux_hppa_has_sethostname 1
#define __linux_loongarch64_has_sethostname 1
#define __linux_m68k_has_sethostname 1
#define __linux_microblaze_has_sethostname 1
#define __linux_mips32_has_sethostname 1
#define __linux_mips64_has_sethostname 1
#define __linux_nios2_has_sethostname 1
#define __linux_or1k_has_sethostname 1
#define __linux_powerpc32_has_sethostname 1
#define __linux_powerpc64_has_sethostname 1
#define __linux_riscv32_has_sethostname 1
#define __linux_riscv64_has_sethostname 1
#define __linux_s390x_has_sethostname 1
#define __linux_sh4_has_sethostname 1
#define __linux_sparc32_has_sethostname 1
#define __linux_sparc64_has_sethostname 1
#define __linux_x64_has_sethostname 1
#define __linux_x86_has_sethostname 1
#define __linux_xtensa_has_sethostname 1
#define __netbsd_alpha_has_sethostname 0
#define __netbsd_arm32_has_sethostname 0
#define __netbsd_arm64_has_sethostname 0
#define __netbsd_generic_has_sethostname 0
#define __netbsd_hppa_has_sethostname 0
#define __netbsd_ia64_has_sethostname 0
#define __netbsd_powerpc32_has_sethostname 0
#define __netbsd_powerpc64_has_sethostname 0
#define __netbsd_riscv32_has_sethostname 0
#define __netbsd_riscv64_has_sethostname 0
#define __netbsd_sparc32_has_sethostname 0
#define __netbsd_sparc64_has_sethostname 0
#define __netbsd_vax_has_sethostname 0
#define __netbsd_x64_has_sethostname 0
#define __netbsd_x86_has_sethostname 0
#define __openbsd_generic_has_sethostname 0
#define __openbsd_x64_has_sethostname 0
#define __openbsd_x86_has_sethostname 0

/* check SYS_setitimer */
#define __darwin_arm64_has_setitimer 0
#define __darwin_generic_has_setitimer 0
#define __darwin_x64_has_setitimer 0
#define __dragonfly_generic_has_setitimer 1
#define __dragonfly_x64_has_setitimer 1
#define __dragonfly_x86_has_setitimer 1
#define __freebsd_generic_has_setitimer 1
#define __freebsd_x64_has_setitimer 1
#define __freebsd_x86_has_setitimer 1
#define __linux_alpha_has_setitimer 1
#define __linux_arc_has_setitimer 1
#define __linux_arm32_has_setitimer 1
#define __linux_arm64_has_setitimer 1
#define __linux_csky_has_setitimer 1
#define __linux_generic_has_setitimer 1
#define __linux_hexagon_has_setitimer 1
#define __linux_hppa_has_setitimer 1
#define __linux_loongarch64_has_setitimer 1
#define __linux_m68k_has_setitimer 1
#define __linux_microblaze_has_setitimer 1
#define __linux_mips32_has_setitimer 1
#define __linux_mips64_has_setitimer 1
#define __linux_nios2_has_setitimer 1
#define __linux_or1k_has_setitimer 1
#define __linux_powerpc32_has_setitimer 1
#define __linux_powerpc64_has_setitimer 1
#define __linux_riscv32_has_setitimer 1
#define __linux_riscv64_has_setitimer 1
#define __linux_s390x_has_setitimer 1
#define __linux_sh4_has_setitimer 1
#define __linux_sparc32_has_setitimer 1
#define __linux_sparc64_has_setitimer 1
#define __linux_x64_has_setitimer 1
#define __linux_x86_has_setitimer 1
#define __linux_xtensa_has_setitimer 1
#define __netbsd_alpha_has_setitimer 1
#define __netbsd_arm32_has_setitimer 1
#define __netbsd_arm64_has_setitimer 1
#define __netbsd_generic_has_setitimer 1
#define __netbsd_hppa_has_setitimer 1
#define __netbsd_ia64_has_setitimer 1
#define __netbsd_powerpc32_has_setitimer 1
#define __netbsd_powerpc64_has_setitimer 1
#define __netbsd_riscv32_has_setitimer 1
#define __netbsd_riscv64_has_setitimer 1
#define __netbsd_sparc32_has_setitimer 1
#define __netbsd_sparc64_has_setitimer 1
#define __netbsd_vax_has_setitimer 1
#define __netbsd_x64_has_setitimer 1
#define __netbsd_x86_has_setitimer 1
#define __openbsd_generic_has_setitimer 0
#define __openbsd_x64_has_setitimer 0
#define __openbsd_x86_has_setitimer 0

/* check SYS_settimeofday */
#define __darwin_arm64_has_settimeofday 1
#define __darwin_generic_has_settimeofday 1
#define __darwin_x64_has_settimeofday 1
#define __dragonfly_generic_has_settimeofday 1
#define __dragonfly_x64_has_settimeofday 1
#define __dragonfly_x86_has_settimeofday 1
#define __freebsd_generic_has_settimeofday 1
#define __freebsd_x64_has_settimeofday 1
#define __freebsd_x86_has_settimeofday 1
#define __linux_alpha_has_settimeofday 1
#define __linux_arc_has_settimeofday 1
#define __linux_arm32_has_settimeofday 1
#define __linux_arm64_has_settimeofday 1
#define __linux_csky_has_settimeofday 1
#define __linux_generic_has_settimeofday 1
#define __linux_hexagon_has_settimeofday 1
#define __linux_hppa_has_settimeofday 1
#define __linux_loongarch64_has_settimeofday 1
#define __linux_m68k_has_settimeofday 1
#define __linux_microblaze_has_settimeofday 1
#define __linux_mips32_has_settimeofday 1
#define __linux_mips64_has_settimeofday 1
#define __linux_nios2_has_settimeofday 1
#define __linux_or1k_has_settimeofday 1
#define __linux_powerpc32_has_settimeofday 1
#define __linux_powerpc64_has_settimeofday 1
#define __linux_riscv32_has_settimeofday 1
#define __linux_riscv64_has_settimeofday 1
#define __linux_s390x_has_settimeofday 1
#define __linux_sh4_has_settimeofday 1
#define __linux_sparc32_has_settimeofday 1
#define __linux_sparc64_has_settimeofday 1
#define __linux_x64_has_settimeofday 1
#define __linux_x86_has_settimeofday 1
#define __linux_xtensa_has_settimeofday 1
#define __netbsd_alpha_has_settimeofday 1
#define __netbsd_arm32_has_settimeofday 1
#define __netbsd_arm64_has_settimeofday 1
#define __netbsd_generic_has_settimeofday 1
#define __netbsd_hppa_has_settimeofday 1
#define __netbsd_ia64_has_settimeofday 1
#define __netbsd_powerpc32_has_settimeofday 1
#define __netbsd_powerpc64_has_settimeofday 1
#define __netbsd_riscv32_has_settimeofday 1
#define __netbsd_riscv64_has_settimeofday 1
#define __netbsd_sparc32_has_settimeofday 1
#define __netbsd_sparc64_has_settimeofday 1
#define __netbsd_vax_has_settimeofday 1
#define __netbsd_x64_has_settimeofday 1
#define __netbsd_x86_has_settimeofday 1
#define __openbsd_generic_has_settimeofday 0
#define __openbsd_x64_has_settimeofday 0
#define __openbsd_x86_has_settimeofday 0

/* check SYS_stat */
#define __darwin_arm64_has_stat 0
#define __darwin_generic_has_stat 0
#define __darwin_x64_has_stat 0
#define __dragonfly_generic_has_stat 1
#define __dragonfly_x64_has_stat 1
#define __dragonfly_x86_has_stat 1
#define __freebsd_generic_has_stat 1
#define __freebsd_x64_has_stat 1
#define __freebsd_x86_has_stat 1
#define __linux_alpha_has_stat 0
#define __linux_arc_has_stat 0
#define __linux_arm32_has_stat 1
#define __linux_arm64_has_stat 0
#define __linux_csky_has_stat 0
#define __linux_generic_has_stat 0
#define __linux_hexagon_has_stat 0
#define __linux_hppa_has_stat 1
#define __linux_loongarch64_has_stat 0
#define __linux_m68k_has_stat 0
#define __linux_microblaze_has_stat 0
#define __linux_mips32_has_stat 1
#define __linux_mips64_has_stat 1
#define __linux_nios2_has_stat 0
#define __linux_or1k_has_stat 0
#define __linux_powerpc32_has_stat 1
#define __linux_powerpc64_has_stat 1
#define __linux_riscv32_has_stat 0
#define __linux_riscv64_has_stat 0
#define __linux_s390x_has_stat 1
#define __linux_sh4_has_stat 1
#define __linux_sparc32_has_stat 1
#define __linux_sparc64_has_stat 1
#define __linux_x64_has_stat 1
#define __linux_x86_has_stat 1
#define __linux_xtensa_has_stat 1
#define __netbsd_alpha_has_stat 1
#define __netbsd_arm32_has_stat 1
#define __netbsd_arm64_has_stat 1
#define __netbsd_generic_has_stat 1
#define __netbsd_hppa_has_stat 1
#define __netbsd_ia64_has_stat 1
#define __netbsd_powerpc32_has_stat 1
#define __netbsd_powerpc64_has_stat 1
#define __netbsd_riscv32_has_stat 1
#define __netbsd_riscv64_has_stat 1
#define __netbsd_sparc32_has_stat 1
#define __netbsd_sparc64_has_stat 1
#define __netbsd_vax_has_stat 1
#define __netbsd_x64_has_stat 1
#define __netbsd_x86_has_stat 1
#define __openbsd_generic_has_stat 1
#define __openbsd_x64_has_stat 1
#define __openbsd_x86_has_stat 1

/* check SYS_stat64 */
#define __darwin_arm64_has_stat64 1
#define __darwin_generic_has_stat64 1
#define __darwin_x64_has_stat64 1
#define __dragonfly_generic_has_stat64 0
#define __dragonfly_x64_has_stat64 0
#define __dragonfly_x86_has_stat64 0
#define __freebsd_generic_has_stat64 0
#define __freebsd_x64_has_stat64 0
#define __freebsd_x86_has_stat64 0
#define __linux_alpha_has_stat64 0
#define __linux_arc_has_stat64 0
#define __linux_arm32_has_stat64 1
#define __linux_arm64_has_stat64 0
#define __linux_csky_has_stat64 0
#define __linux_generic_has_stat64 0
#define __linux_hexagon_has_stat64 0
#define __linux_hppa_has_stat64 1
#define __linux_loongarch64_has_stat64 0
#define __linux_m68k_has_stat64 0
#define __linux_microblaze_has_stat64 0
#define __linux_mips32_has_stat64 0
#define __linux_mips64_has_stat64 0
#define __linux_nios2_has_stat64 0
#define __linux_or1k_has_stat64 0
#define __linux_powerpc32_has_stat64 1
#define __linux_powerpc64_has_stat64 1
#define __linux_riscv32_has_stat64 0
#define __linux_riscv64_has_stat64 0
#define __linux_s390x_has_stat64 1
#define __linux_sh4_has_stat64 1
#define __linux_sparc32_has_stat64 1
#define __linux_sparc64_has_stat64 1
#define __linux_x64_has_stat64 0
#define __linux_x86_has_stat64 1
#define __linux_xtensa_has_stat64 1
#define __netbsd_alpha_has_stat64 0
#define __netbsd_arm32_has_stat64 0
#define __netbsd_arm64_has_stat64 0
#define __netbsd_generic_has_stat64 0
#define __netbsd_hppa_has_stat64 0
#define __netbsd_ia64_has_stat64 0
#define __netbsd_powerpc32_has_stat64 0
#define __netbsd_powerpc64_has_stat64 0
#define __netbsd_riscv32_has_stat64 0
#define __netbsd_riscv64_has_stat64 0
#define __netbsd_sparc32_has_stat64 0
#define __netbsd_sparc64_has_stat64 0
#define __netbsd_vax_has_stat64 0
#define __netbsd_x64_has_stat64 0
#define __netbsd_x86_has_stat64 0
#define __openbsd_generic_has_stat64 0
#define __openbsd_x64_has_stat64 0
#define __openbsd_x86_has_stat64 0

/* check SYS_utimensat */
#define __darwin_arm64_has_utimensat 0
#define __darwin_generic_has_utimensat 0
#define __darwin_x64_has_utimensat 0
#define __dragonfly_generic_has_utimensat 1
#define __dragonfly_x64_has_utimensat 1
#define __dragonfly_x86_has_utimensat 1
#define __freebsd_generic_has_utimensat 1
#define __freebsd_x64_has_utimensat 1
#define __freebsd_x86_has_utimensat 1
#define __linux_alpha_has_utimensat 1
#define __linux_arc_has_utimensat 1
#define __linux_arm32_has_utimensat 1
#define __linux_arm64_has_utimensat 1
#define __linux_csky_has_utimensat 1
#define __linux_generic_has_utimensat 1
#define __linux_hexagon_has_utimensat 1
#define __linux_hppa_has_utimensat 1
#define __linux_loongarch64_has_utimensat 1
#define __linux_m68k_has_utimensat 1
#define __linux_microblaze_has_utimensat 1
#define __linux_mips32_has_utimensat 1
#define __linux_mips64_has_utimensat 1
#define __linux_nios2_has_utimensat 1
#define __linux_or1k_has_utimensat 1
#define __linux_powerpc32_has_utimensat 1
#define __linux_powerpc64_has_utimensat 1
#define __linux_riscv32_has_utimensat 1
#define __linux_riscv64_has_utimensat 1
#define __linux_s390x_has_utimensat 1
#define __linux_sh4_has_utimensat 1
#define __linux_sparc32_has_utimensat 1
#define __linux_sparc64_has_utimensat 1
#define __linux_x64_has_utimensat 1
#define __linux_x86_has_utimensat 1
#define __linux_xtensa_has_utimensat 1
#define __netbsd_alpha_has_utimensat 1
#define __netbsd_arm32_has_utimensat 1
#define __netbsd_arm64_has_utimensat 1
#define __netbsd_generic_has_utimensat 1
#define __netbsd_hppa_has_utimensat 1
#define __netbsd_ia64_has_utimensat 1
#define __netbsd_powerpc32_has_utimensat 1
#define __netbsd_powerpc64_has_utimensat 1
#define __netbsd_riscv32_has_utimensat 1
#define __netbsd_riscv64_has_utimensat 1
#define __netbsd_sparc32_has_utimensat 1
#define __netbsd_sparc64_has_utimensat 1
#define __netbsd_vax_has_utimensat 1
#define __netbsd_x64_has_utimensat 1
#define __netbsd_x86_has_utimensat 1
#define __openbsd_generic_has_utimensat 0
#define __openbsd_x64_has_utimensat 0
#define __openbsd_x86_has_utimensat 0

/* check SYS_utimes */
#define __darwin_arm64_has_utimes 0
#define __darwin_generic_has_utimes 0
#define __darwin_x64_has_utimes 0
#define __dragonfly_generic_has_utimes 0
#define __dragonfly_x64_has_utimes 0
#define __dragonfly_x86_has_utimes 0
#define __freebsd_generic_has_utimes 1
#define __freebsd_x64_has_utimes 1
#define __freebsd_x86_has_utimes 1
#define __linux_alpha_has_utimes 0
#define __linux_arc_has_utimes 0
#define __linux_arm32_has_utimes 1
#define __linux_arm64_has_utimes 0
#define __linux_csky_has_utimes 0
#define __linux_generic_has_utimes 0
#define __linux_hexagon_has_utimes 0
#define __linux_hppa_has_utimes 1
#define __linux_loongarch64_has_utimes 0
#define __linux_m68k_has_utimes 0
#define __linux_microblaze_has_utimes 0
#define __linux_mips32_has_utimes 1
#define __linux_mips64_has_utimes 1
#define __linux_nios2_has_utimes 0
#define __linux_or1k_has_utimes 0
#define __linux_powerpc32_has_utimes 1
#define __linux_powerpc64_has_utimes 1
#define __linux_riscv32_has_utimes 0
#define __linux_riscv64_has_utimes 0
#define __linux_s390x_has_utimes 1
#define __linux_sh4_has_utimes 1
#define __linux_sparc32_has_utimes 1
#define __linux_sparc64_has_utimes 1
#define __linux_x64_has_utimes 1
#define __linux_x86_has_utimes 1
#define __linux_xtensa_has_utimes 1
#define __netbsd_alpha_has_utimes 1
#define __netbsd_arm32_has_utimes 1
#define __netbsd_arm64_has_utimes 1
#define __netbsd_generic_has_utimes 1
#define __netbsd_hppa_has_utimes 1
#define __netbsd_ia64_has_utimes 1
#define __netbsd_powerpc32_has_utimes 1
#define __netbsd_powerpc64_has_utimes 1
#define __netbsd_riscv32_has_utimes 1
#define __netbsd_riscv64_has_utimes 1
#define __netbsd_sparc32_has_utimes 1
#define __netbsd_sparc64_has_utimes 1
#define __netbsd_vax_has_utimes 1
#define __netbsd_x64_has_utimes 1
#define __netbsd_x86_has_utimes 1
#define __openbsd_generic_has_utimes 0
#define __openbsd_x64_has_utimes 0
#define __openbsd_x86_has_utimes 0
