/**
 * OPENBSD SYSCALLS IMPORTED  //  last updated: 2026-05-25 20:50:24 UTC
 * https://cvsweb.openbsd.org/checkout/src/sys/kern/syscalls.master
 */

X(SYS_exit, 1, exit, void, (int), (int)a0)
X(SYS_fork, 2, fork, int, (void))
X(SYS_read, 3, read, ssize_t, (int, void *, size_t), (int)a0, (void *)a1, (size_t)a2)
X(SYS_write, 4, write, ssize_t, (int, const void *, size_t), (int)a0, (const void *)a1, (size_t)a2)
X(SYS_open, 5, open, int, (const char *, int, ... mode_t), (const char *)a0, (int)a1, (... mode_t)a2)
X(SYS_close, 6, close, int, (int), (int)a0)
X(SYS_getentropy, 7, getentropy, int, (void *, size_t), (void *)a0, (size_t)a1)
X(SYS___tfork, 8, __tfork, int, (const struct __tfork *, size_t), (const struct __tfork *)a0, (size_t)a1)
X(SYS_link, 9, link, int, (const char *, const char *), (const char *)a0, (const char *)a1)
X(SYS_unlink, 10, unlink, int, (const char *), (const char *)a0)
X(SYS_wait4, 11, wait4, pid_t, (pid_t, int *, int, struct rusage *), (pid_t)a0, (int *)a1, (int)a2, (struct rusage *)a3)
X(SYS_chdir, 12, chdir, int, (const char *), (const char *)a0)
X(SYS_fchdir, 13, fchdir, int, (int), (int)a0)
X(SYS_mknod, 14, mknod, int, (const char *, mode_t, dev_t), (const char *)a0, (mode_t)a1, (dev_t)a2)
X(SYS_chmod, 15, chmod, int, (const char *, mode_t), (const char *)a0, (mode_t)a1)
X(SYS_chown, 16, chown, int, (const char *, uid_t, gid_t), (const char *)a0, (uid_t)a1, (gid_t)a2)
X(SYS_obreak, 17, obreak, int, (char *), (char *)a0)
X(SYS_getdtablecount, 18, getdtablecount, int, (void))
X(SYS_getrusage, 19, getrusage, int, (int, struct rusage *), (int)a0, (struct rusage *)a1)
X(SYS_getpid, 20, getpid, pid_t, (void))
X(SYS_mount, 21, mount, int, (const char *, const char *, int, void *), (const char *)a0, (const char *)a1, (int)a2, (void *)a3)
X(SYS_unmount, 22, unmount, int, (const char *, int), (const char *)a0, (int)a1)
X(SYS_setuid, 23, setuid, int, (uid_t), (uid_t)a0)
X(SYS_getuid, 24, getuid, uid_t, (void))
X(SYS_geteuid, 25, geteuid, uid_t, (void))
X(SYS_ptrace, 26, ptrace, int, (int, pid_t, caddr_t, int), (int)a0, (pid_t)a1, (caddr_t)a2, (int)a3)
X(SYS_recvmsg, 27, recvmsg, ssize_t, (int, struct msghdr *, int), (int)a0, (struct msghdr *)a1, (int)a2)
X(SYS_sendmsg, 28, sendmsg, ssize_t, (int, const struct msghdr *, int), (int)a0, (const struct msghdr *)a1, (int)a2)
X(SYS_recvfrom, 29, recvfrom, ssize_t, (int, void *, size_t, int, struct sockaddr *, socklen_t *), (int)a0, (void *)a1, (size_t)a2, (int)a3, (struct sockaddr *)a4, (socklen_t *)a5)
X(SYS_accept, 30, accept, int, (int, struct sockaddr *, socklen_t *), (int)a0, (struct sockaddr *)a1, (socklen_t *)a2)
X(SYS_getpeername, 31, getpeername, int, (int, struct sockaddr *, socklen_t *), (int)a0, (struct sockaddr *)a1, (socklen_t *)a2)
X(SYS_getsockname, 32, getsockname, int, (int, struct sockaddr *, socklen_t *), (int)a0, (struct sockaddr *)a1, (socklen_t *)a2)
X(SYS_access, 33, access, int, (const char *, int), (const char *)a0, (int)a1)
X(SYS_chflags, 34, chflags, int, (const char *, u_int), (const char *)a0, (u_int)a1)
X(SYS_fchflags, 35, fchflags, int, (int, u_int), (int)a0, (u_int)a1)
X(SYS_sync, 36, sync, void, (void))
X(SYS_stat, 38, stat, int, (const char *, struct stat *), (const char *)a0, (struct stat *)a1)
X(SYS_getppid, 39, getppid, pid_t, (void))
X(SYS_lstat, 40, lstat, int, (const char *, struct stat *), (const char *)a0, (struct stat *)a1)
X(SYS_dup, 41, dup, int, (int), (int)a0)
X(SYS_fstatat, 42, fstatat, int, (int, const char *, struct stat *, int), (int)a0, (const char *)a1, (struct stat *)a2, (int)a3)
X(SYS_getegid, 43, getegid, gid_t, (void))
X(SYS_ktrace, 45, ktrace, int, (const char *, int, int, pid_t), (const char *)a0, (int)a1, (int)a2, (pid_t)a3)
X(SYS_sigaction, 46, sigaction, int, (int, const struct sigaction *, struct sigaction *), (int)a0, (const struct sigaction *)a1, (struct sigaction *)a2)
X(SYS_getgid, 47, getgid, gid_t, (void))
X(SYS_sigprocmask, 48, sigprocmask, int, (int, sigset_t), (int)a0, (sigset_t)a1)
X(SYS_setlogin, 50, setlogin, int, (const char *), (const char *)a0)
X(SYS_acct, 51, acct, int, (const char *), (const char *)a0)
X(SYS_sigpending, 52, sigpending, int, (void))
X(SYS_fstat, 53, fstat, int, (int, struct stat *), (int)a0, (struct stat *)a1)
X(SYS_ioctl, 54, ioctl, int, (int, u_long, ... void *), (int)a0, (u_long)a1, (... void *)a2)
X(SYS_reboot, 55, reboot, int, (int), (int)a0)
X(SYS_revoke, 56, revoke, int, (const char *), (const char *)a0)
X(SYS_symlink, 57, symlink, int, (const char *, const char *), (const char *)a0, (const char *)a1)
X(SYS_readlink, 58, readlink, ssize_t, (const char *, char *, size_t), (const char *)a0, (char *)a1, (size_t)a2)
X(SYS_execve, 59, execve, int, (const char *, char * const *, char * const *), (const char *)a0, (char * const *)a1, (char * const *)a2)
X(SYS_umask, 60, umask, mode_t, (mode_t), (mode_t)a0)
X(SYS_chroot, 61, chroot, int, (const char *), (const char *)a0)
X(SYS_getfsstat, 62, getfsstat, int, (struct statfs *, size_t, int), (struct statfs *)a0, (size_t)a1, (int)a2)
X(SYS_statfs, 63, statfs, int, (const char *, struct statfs *), (const char *)a0, (struct statfs *)a1)
X(SYS_fstatfs, 64, fstatfs, int, (int, struct statfs *), (int)a0, (struct statfs *)a1)
X(SYS_fhstatfs, 65, fhstatfs, int, (const fhandle_t *, struct statfs *), (const fhandle_t *)a0, (struct statfs *)a1)
X(SYS_vfork, 66, vfork, int, (void))
X(SYS_gettimeofday, 67, gettimeofday, int, (struct timeval *, struct timezone *), (struct timeval *)a0, (struct timezone *)a1)
X(SYS_settimeofday, 68, settimeofday, int, (const struct timeval *, const struct timezone *), (const struct timeval *)a0, (const struct timezone *)a1)
X(SYS_setitimer, 69, setitimer, int, (int, const struct itimerval *, struct itimerval *), (int)a0, (const struct itimerval *)a1, (struct itimerval *)a2)
X(SYS_getitimer, 70, getitimer, int, (int, struct itimerval *), (int)a0, (struct itimerval *)a1)
X(SYS_select, 71, select, int, (int, fd_set *, fd_set *, fd_set *, struct timeval *), (int)a0, (fd_set *)a1, (fd_set *)a2, (fd_set *)a3, (struct timeval *)a4)
X(SYS_kevent, 72, kevent, int, (int, const struct kevent *, int, struct kevent *, int, const struct timespec *), (int)a0, (const struct kevent *)a1, (int)a2, (struct kevent *)a3, (int)a4, (const struct timespec *)a5)
X(SYS_munmap, 73, munmap, int, (void *, size_t), (void *)a0, (size_t)a1)
X(SYS_mprotect, 74, mprotect, int, (void *, size_t, int), (void *)a0, (size_t)a1, (int)a2)
X(SYS_madvise, 75, madvise, int, (void *, size_t, int), (void *)a0, (size_t)a1, (int)a2)
X(SYS_utimes, 76, utimes, int, (const char *, const struct timeval *), (const char *)a0, (const struct timeval *)a1)
X(SYS_futimes, 77, futimes, int, (int, const struct timeval *), (int)a0, (const struct timeval *)a1)
X(SYS_getgroups, 79, getgroups, int, (int, gid_t *), (int)a0, (gid_t *)a1)
X(SYS_setgroups, 80, setgroups, int, (int, const gid_t *), (int)a0, (const gid_t *)a1)
X(SYS_getpgrp, 81, getpgrp, int, (void))
X(SYS_setpgid, 82, setpgid, int, (pid_t, pid_t), (pid_t)a0, (pid_t)a1)
X(SYS_futex, 83, futex, int, (uint32_t *, int, int, const struct timespec *, uint32_t *), (uint32_t *)a0, (int)a1, (int)a2, (const struct timespec *)a3, (uint32_t *)a4)
X(SYS_utimensat, 84, utimensat, int, (int, const char *, const struct timespec *, int), (int)a0, (const char *)a1, (const struct timespec *)a2, (int)a3)
X(SYS_futimens, 85, futimens, int, (int, const struct timespec *), (int)a0, (const struct timespec *)a1)
X(SYS_kbind, 86, kbind, int, (const struct __kbind *, size_t, int64_t), (const struct __kbind *)a0, (size_t)a1, (int64_t)a2)
X(SYS_clock_gettime, 87, clock_gettime, int, (clockid_t, struct timespec *), (clockid_t)a0, (struct timespec *)a1)
X(SYS_clock_settime, 88, clock_settime, int, (clockid_t, const struct timespec *), (clockid_t)a0, (const struct timespec *)a1)
X(SYS_clock_getres, 89, clock_getres, int, (clockid_t, struct timespec *), (clockid_t)a0, (struct timespec *)a1)
X(SYS_dup2, 90, dup2, int, (int, int), (int)a0, (int)a1)
X(SYS_nanosleep, 91, nanosleep, int, (const struct timespec *, struct timespec *), (const struct timespec *)a0, (struct timespec *)a1)
X(SYS_fcntl, 92, fcntl, int, (int, int, ... void *), (int)a0, (int)a1, (... void *)a2)
X(SYS_accept4, 93, accept4, int, (int, struct sockaddr *, socklen_t *, int), (int)a0, (struct sockaddr *)a1, (socklen_t *)a2, (int)a3)
X(SYS___thrsleep, 94, __thrsleep, int, (const volatile void *, clockid_t, const struct timespec *, void *, const int *), (const volatile void *)a0, (clockid_t)a1, (const struct timespec *)a2, (void *)a3, (const int *)a4)
X(SYS_fsync, 95, fsync, int, (int), (int)a0)
X(SYS_setpriority, 96, setpriority, int, (int, id_t, int), (int)a0, (id_t)a1, (int)a2)
X(SYS_socket, 97, socket, int, (int, int, int), (int)a0, (int)a1, (int)a2)
X(SYS_connect, 98, connect, int, (int, const struct sockaddr *, socklen_t), (int)a0, (const struct sockaddr *)a1, (socklen_t)a2)
X(SYS_getdents, 99, getdents, int, (int, void *, size_t), (int)a0, (void *)a1, (size_t)a2)
X(SYS_getpriority, 100, getpriority, int, (int, id_t), (int)a0, (id_t)a1)
X(SYS_pipe2, 101, pipe2, int, (int *, int), (int *)a0, (int)a1)
X(SYS_dup3, 102, dup3, int, (int, int, int), (int)a0, (int)a1, (int)a2)
X(SYS_sigreturn, 103, sigreturn, int, (struct sigcontext *), (struct sigcontext *)a0)
X(SYS_bind, 104, bind, int, (int, const struct sockaddr *, socklen_t), (int)a0, (const struct sockaddr *)a1, (socklen_t)a2)
X(SYS_setsockopt, 105, setsockopt, int, (int, int, int, const void *, socklen_t), (int)a0, (int)a1, (int)a2, (const void *)a3, (socklen_t)a4)
X(SYS_listen, 106, listen, int, (int, int), (int)a0, (int)a1)
X(SYS_chflagsat, 107, chflagsat, int, (int, const char *, u_int, int), (int)a0, (const char *)a1, (u_int)a2, (int)a3)
X(SYS_pledge, 108, pledge, int, (const char *, const char *), (const char *)a0, (const char *)a1)
X(SYS_ppoll, 109, ppoll, int, (struct pollfd *, u_int, const struct timespec *, const sigset_t *), (struct pollfd *)a0, (u_int)a1, (const struct timespec *)a2, (const sigset_t *)a3)
X(SYS_pselect, 110, pselect, int, (int, fd_set *, fd_set *, fd_set *, const struct timespec *, const sigset_t *), (int)a0, (fd_set *)a1, (fd_set *)a2, (fd_set *)a3, (const struct timespec *)a4, (const sigset_t *)a5)
X(SYS_sigsuspend, 111, sigsuspend, int, (int), (int)a0)
X(SYS_sendsyslog, 112, sendsyslog, int, (const char *, size_t, int), (const char *)a0, (size_t)a1, (int)a2)
X(SYS_unveil, 114, unveil, int, (const char *, const char *), (const char *)a0, (const char *)a1)
X(SYS___realpath, 115, __realpath, int, (const char *, char *), (const char *)a0, (char *)a1)
X(SYS_recvmmsg, 116, recvmmsg, int, (int, struct mmsghdr *, unsigned int, int, struct timespec *), (int)a0, (struct mmsghdr *)a1, (unsigned int)a2, (int)a3, (struct timespec *)a4)
X(SYS_sendmmsg, 117, sendmmsg, int, (int, struct mmsghdr *, unsigned int, int), (int)a0, (struct mmsghdr *)a1, (unsigned int)a2, (int)a3)
X(SYS_getsockopt, 118, getsockopt, int, (int, int, int, void *, socklen_t *), (int)a0, (int)a1, (int)a2, (void *)a3, (socklen_t *)a4)
X(SYS_thrkill, 119, thrkill, int, (pid_t, int, void *), (pid_t)a0, (int)a1, (void *)a2)
X(SYS_readv, 120, readv, ssize_t, (int, const struct iovec *, int), (int)a0, (const struct iovec *)a1, (int)a2)
X(SYS_writev, 121, writev, ssize_t, (int, const struct iovec *, int), (int)a0, (const struct iovec *)a1, (int)a2)
X(SYS_kill, 122, kill, int, (int, int), (int)a0, (int)a1)
X(SYS_fchown, 123, fchown, int, (int, uid_t, gid_t), (int)a0, (uid_t)a1, (gid_t)a2)
X(SYS_fchmod, 124, fchmod, int, (int, mode_t), (int)a0, (mode_t)a1)
X(SYS___pledge_open, 125, __pledge_open, int, (const char *, int, ... mode_t), (const char *)a0, (int)a1, (... mode_t)a2)
X(SYS_setreuid, 126, setreuid, int, (uid_t, uid_t), (uid_t)a0, (uid_t)a1)
X(SYS_setregid, 127, setregid, int, (gid_t, gid_t), (gid_t)a0, (gid_t)a1)
X(SYS_rename, 128, rename, int, (const char *, const char *), (const char *)a0, (const char *)a1)
X(SYS_flock, 131, flock, int, (int, int), (int)a0, (int)a1)
X(SYS_mkfifo, 132, mkfifo, int, (const char *, mode_t), (const char *)a0, (mode_t)a1)
X(SYS_sendto, 133, sendto, ssize_t, (int, const void *, size_t, int, const struct sockaddr *, socklen_t), (int)a0, (const void *)a1, (size_t)a2, (int)a3, (const struct sockaddr *)a4, (socklen_t)a5)
X(SYS_shutdown, 134, shutdown, int, (int, int), (int)a0, (int)a1)
X(SYS_socketpair, 135, socketpair, int, (int, int, int, int *), (int)a0, (int)a1, (int)a2, (int *)a3)
X(SYS_mkdir, 136, mkdir, int, (const char *, mode_t), (const char *)a0, (mode_t)a1)
X(SYS_rmdir, 137, rmdir, int, (const char *), (const char *)a0)
X(SYS_adjtime, 140, adjtime, int, (const struct timeval *, struct timeval *), (const struct timeval *)a0, (struct timeval *)a1)
X(SYS_getlogin_r, 141, getlogin_r, int, (char *, size_t), (char *)a0, (size_t)a1)
X(SYS_getthrname, 142, getthrname, int, (pid_t, char *, size_t), (pid_t)a0, (char *)a1, (size_t)a2)
X(SYS_setthrname, 143, setthrname, int, (pid_t, const char *), (pid_t)a0, (const char *)a1)
X(SYS_setsid, 147, setsid, int, (void))
X(SYS_quotactl, 148, quotactl, int, (const char *, int, int, char *), (const char *)a0, (int)a1, (int)a2, (char *)a3)
X(SYS_ypconnect, 150, ypconnect, int, (int), (int)a0)
X(SYS_nfssvc, 155, nfssvc, int, (int, void *), (int)a0, (void *)a1)
X(SYS_pinsyscalls, 158, pinsyscalls, int, (void *, size_t, u_int *, int), (void *)a0, (size_t)a1, (u_int *)a2, (int)a3)
X(SYS_mimmutable, 159, mimmutable, int, (void *, size_t), (void *)a0, (size_t)a1)
X(SYS_waitid, 160, waitid, int, (int, id_t, siginfo_t *, int), (int)a0, (id_t)a1, (siginfo_t *)a2, (int)a3)
X(SYS_getfh, 161, getfh, int, (const char *, fhandle_t *), (const char *)a0, (fhandle_t *)a1)
X(SYS___tmpfd, 164, __tmpfd, int, (int), (int)a0)
X(SYS_sysarch, 165, sysarch, int, (int, void *), (int)a0, (void *)a1)
X(SYS_lseek, 166, lseek, off_t, (int, off_t, int), (int)a0, (off_t)a1, (int)a2)
X(SYS_truncate, 167, truncate, int, (const char *, off_t), (const char *)a0, (off_t)a1)
X(SYS_ftruncate, 168, ftruncate, int, (int, off_t), (int)a0, (off_t)a1)
X(SYS_pread, 169, pread, ssize_t, (int, void *, size_t, off_t), (int)a0, (void *)a1, (size_t)a2, (off_t)a3)
X(SYS_pwrite, 170, pwrite, ssize_t, (int, const void *, size_t, off_t), (int)a0, (const void *)a1, (size_t)a2, (off_t)a3)
X(SYS_preadv, 171, preadv, ssize_t, (int, const struct iovec *, int, off_t), (int)a0, (const struct iovec *)a1, (int)a2, (off_t)a3)
X(SYS_pwritev, 172, pwritev, ssize_t, (int, const struct iovec *, int, off_t), (int)a0, (const struct iovec *)a1, (int)a2, (off_t)a3)
X(SYS_profil, 175, profil, int, (void *, size_t, size_t, u_long, u_int, int), (void *)a0, (size_t)a1, (size_t)a2, (u_long)a3, (u_int)a4, (int)a5)
X(SYS_setgid, 181, setgid, int, (gid_t), (gid_t)a0)
X(SYS_setegid, 182, setegid, int, (gid_t), (gid_t)a0)
X(SYS_seteuid, 183, seteuid, int, (uid_t), (uid_t)a0)
X(SYS_pathconfat, 190, pathconfat, long, (int, const char *, int, int), (int)a0, (const char *)a1, (int)a2, (int)a3)
X(SYS_pathconf, 191, pathconf, long, (const char *, int), (const char *)a0, (int)a1)
X(SYS_fpathconf, 192, fpathconf, long, (int, int), (int)a0, (int)a1)
X(SYS_swapctl, 193, swapctl, int, (int, const void *, int), (int)a0, (const void *)a1, (int)a2)
X(SYS_getrlimit, 194, getrlimit, int, (int, struct rlimit *), (int)a0, (struct rlimit *)a1)
X(SYS_setrlimit, 195, setrlimit, int, (int, const struct rlimit *), (int)a0, (const struct rlimit *)a1)
X(SYS_sysctl, 202, sysctl, int, (const int *, u_int, void *, size_t *, void *, size_t), (const int *)a0, (u_int)a1, (void *)a2, (size_t *)a3, (void *)a4, (size_t)a5)
X(SYS_mlock, 203, mlock, int, (const void *, size_t), (const void *)a0, (size_t)a1)
X(SYS_munlock, 204, munlock, int, (const void *, size_t), (const void *)a0, (size_t)a1)
X(SYS_getpgid, 207, getpgid, pid_t, (pid_t), (pid_t)a0)
X(SYS_utrace, 209, utrace, int, (const char *, const void *, size_t), (const char *)a0, (const void *)a1, (size_t)a2)
X(SYS_semget, 221, semget, int, (key_t, int, int), (key_t)a0, (int)a1, (int)a2)
X(SYS_msgget, 225, msgget, int, (key_t, int), (key_t)a0, (int)a1)
X(SYS_msgsnd, 226, msgsnd, int, (int, const void *, size_t, int), (int)a0, (const void *)a1, (size_t)a2, (int)a3)
X(SYS_msgrcv, 227, msgrcv, int, (int, void *, size_t, long, int), (int)a0, (void *)a1, (size_t)a2, (long)a3, (int)a4)
X(SYS_shmdt, 230, shmdt, int, (const void *), (const void *)a0)
X(SYS_minherit, 250, minherit, int, (void *, size_t, int), (void *)a0, (size_t)a1, (int)a2)
X(SYS_poll, 252, poll, int, (struct pollfd *, u_int, int), (struct pollfd *)a0, (u_int)a1, (int)a2)
X(SYS_issetugid, 253, issetugid, int, (void))
X(SYS_lchown, 254, lchown, int, (const char *, uid_t, gid_t), (const char *)a0, (uid_t)a1, (gid_t)a2)
X(SYS_getsid, 255, getsid, pid_t, (pid_t), (pid_t)a0)
X(SYS_msync, 256, msync, int, (void *, size_t, int), (void *)a0, (size_t)a1, (int)a2)
X(SYS_pipe, 263, pipe, int, (int *), (int *)a0)
X(SYS_fhopen, 264, fhopen, int, (const fhandle_t *, int), (const fhandle_t *)a0, (int)a1)
X(SYS_kqueue, 269, kqueue, int, (void))
X(SYS_kqueue1, 270, kqueue1, int, (int), (int)a0)
X(SYS_mlockall, 271, mlockall, int, (int), (int)a0)
X(SYS_munlockall, 272, munlockall, int, (void))
X(SYS_getresuid, 281, getresuid, int, (uid_t *, uid_t *, uid_t *), (uid_t *)a0, (uid_t *)a1, (uid_t *)a2)
X(SYS_setresuid, 282, setresuid, int, (uid_t, uid_t, uid_t), (uid_t)a0, (uid_t)a1, (uid_t)a2)
X(SYS_getresgid, 283, getresgid, int, (gid_t *, gid_t *, gid_t *), (gid_t *)a0, (gid_t *)a1, (gid_t *)a2)
X(SYS_setresgid, 284, setresgid, int, (gid_t, gid_t, gid_t), (gid_t)a0, (gid_t)a1, (gid_t)a2)
X(SYS_closefrom, 287, closefrom, int, (int), (int)a0)
X(SYS_sigaltstack, 288, sigaltstack, int, (const struct sigaltstack *, struct sigaltstack *), (const struct sigaltstack *)a0, (struct sigaltstack *)a1)
X(SYS_shmget, 289, shmget, int, (key_t, size_t, int), (key_t)a0, (size_t)a1, (int)a2)
X(SYS_semop, 290, semop, int, (int, struct sembuf *, size_t), (int)a0, (struct sembuf *)a1, (size_t)a2)
X(SYS_fhstat, 294, fhstat, int, (const fhandle_t *, struct stat *), (const fhandle_t *)a0, (struct stat *)a1)
X(SYS___semctl, 295, __semctl, int, (int, int, int, union semun *), (int)a0, (int)a1, (int)a2, (union semun *)a3)
X(SYS_shmctl, 296, shmctl, int, (int, int, struct shmid_ds *), (int)a0, (int)a1, (struct shmid_ds *)a2)
X(SYS_msgctl, 297, msgctl, int, (int, int, struct msqid_ds *), (int)a0, (int)a1, (struct msqid_ds *)a2)
X(SYS_sched_yield, 298, sched_yield, int, (void))
X(SYS_getthrid, 299, getthrid, pid_t, (void))
X(SYS___thrwakeup, 301, __thrwakeup, int, (const volatile void *, int), (const volatile void *)a0, (int)a1)
X(SYS___threxit, 302, __threxit, void, (pid_t *), (pid_t *)a0)
X(SYS___thrsigdivert, 303, __thrsigdivert, int, (sigset_t, siginfo_t *, const struct timespec *), (sigset_t)a0, (siginfo_t *)a1, (const struct timespec *)a2)
X(SYS___getcwd, 304, __getcwd, int, (char *, size_t), (char *)a0, (size_t)a1)
X(SYS_adjfreq, 305, adjfreq, int, (const int64_t *, int64_t *), (const int64_t *)a0, (int64_t *)a1)
X(SYS_setrtable, 310, setrtable, int, (int), (int)a0)
X(SYS_getrtable, 311, getrtable, int, (void))
X(SYS_faccessat, 313, faccessat, int, (int, const char *, int, int), (int)a0, (const char *)a1, (int)a2, (int)a3)
X(SYS_fchmodat, 314, fchmodat, int, (int, const char *, mode_t, int), (int)a0, (const char *)a1, (mode_t)a2, (int)a3)
X(SYS_fchownat, 315, fchownat, int, (int, const char *, uid_t, gid_t, int), (int)a0, (const char *)a1, (uid_t)a2, (gid_t)a3, (int)a4)
X(SYS_linkat, 317, linkat, int, (int, const char *, int, const char *, int), (int)a0, (const char *)a1, (int)a2, (const char *)a3, (int)a4)
X(SYS_mkdirat, 318, mkdirat, int, (int, const char *, mode_t), (int)a0, (const char *)a1, (mode_t)a2)
X(SYS_mkfifoat, 319, mkfifoat, int, (int, const char *, mode_t), (int)a0, (const char *)a1, (mode_t)a2)
X(SYS_mknodat, 320, mknodat, int, (int, const char *, mode_t, dev_t), (int)a0, (const char *)a1, (mode_t)a2, (dev_t)a3)
X(SYS_openat, 321, openat, int, (int, const char *, int, ... mode_t), (int)a0, (const char *)a1, (int)a2, (... mode_t)a3)
X(SYS_readlinkat, 322, readlinkat, ssize_t, (int, const char *, char *, size_t), (int)a0, (const char *)a1, (char *)a2, (size_t)a3)
X(SYS_renameat, 323, renameat, int, (int, const char *, int, const char *), (int)a0, (const char *)a1, (int)a2, (const char *)a3)
X(SYS_symlinkat, 324, symlinkat, int, (const char *, int, const char *), (const char *)a0, (int)a1, (const char *)a2)
X(SYS_unlinkat, 325, unlinkat, int, (int, const char *, int), (int)a0, (const char *)a1, (int)a2)
X(SYS___set_tcb, 329, __set_tcb, void, (void *), (void *)a0)
