/**
 * OPENBSD SYSCALLS IMPORTED  //  last updated: 2025-11-28 20:09:30 UTC
 * https://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/src/sys/kern/syscalls.master
 */

X(SYS_exit, 1, exit, void, (int), (int)a0)
X(SYS_fork, 2, fork, int, (void))
X(SYS_read, 3, read, ssize_t, (int, void *, size_t), (int)a0, (void *)a1, (size_t)a2)
X(SYS_close, 6, close, int, (int), (int)a0)
X(SYS_getentropy, 7, getentropy, int, (void *, size_t), (void *)a0, (size_t)a1)
X(SYS_link, 9, link, int, (const char *, const char *), (const char *)a0, (const char *)a1)
X(SYS_unlink, 10, unlink, int, (const char *), (const char *)a0)
X(SYS_chdir, 12, chdir, int, (const char *), (const char *)a0)
X(SYS_fchdir, 13, fchdir, int, (int), (int)a0)
X(SYS_chmod, 15, chmod, int, (const char *, mode_t), (const char *)a0, (mode_t)a1)
X(SYS_obreak, 17, obreak, int, (char *), (char *)a0)
X(SYS_getdtablecount, 18, getdtablecount, int, (void))
X(SYS_getpid, 20, getpid, pid_t, (void))
X(SYS_unmount, 22, unmount, int, (const char *, int), (const char *)a0, (int)a1)
X(SYS_setuid, 23, setuid, int, (uid_t), (uid_t)a0)
X(SYS_getuid, 24, getuid, uid_t, (void))
X(SYS_geteuid, 25, geteuid, uid_t, (void))
X(SYS_access, 33, access, int, (const char *, int), (const char *)a0, (int)a1)
X(SYS_chflags, 34, chflags, int, (const char *, u_int), (const char *)a0, (u_int)a1)
X(SYS_fchflags, 35, fchflags, int, (int, u_int), (int)a0, (u_int)a1)
X(SYS_sync, 36, sync, void, (void))
X(SYS_stat, 38, stat, int, (const char *, struct stat *), (const char *)a0, (struct stat *)a1)
X(SYS_getppid, 39, getppid, pid_t, (void))
X(SYS_lstat, 40, lstat, int, (const char *, struct stat *), (const char *)a0, (struct stat *)a1)
X(SYS_dup, 41, dup, int, (int), (int)a0)
X(SYS_getegid, 43, getegid, gid_t, (void))
X(SYS_getgid, 47, getgid, gid_t, (void))
X(SYS_sigprocmask, 48, sigprocmask, int, (int, sigset_t), (int)a0, (sigset_t)a1)
X(SYS_setlogin, 50, setlogin, int, (const char *), (const char *)a0)
X(SYS_acct, 51, acct, int, (const char *), (const char *)a0)
X(SYS_sigpending, 52, sigpending, int, (void))
X(SYS_fstat, 53, fstat, int, (int, struct stat *), (int)a0, (struct stat *)a1)
X(SYS_reboot, 55, reboot, int, (int), (int)a0)
X(SYS_revoke, 56, revoke, int, (const char *), (const char *)a0)
X(SYS_umask, 60, umask, mode_t, (mode_t), (mode_t)a0)
X(SYS_chroot, 61, chroot, int, (const char *), (const char *)a0)
X(SYS_fstatfs, 64, fstatfs, int, (int, struct statfs *), (int)a0, (struct statfs *)a1)
X(SYS_vfork, 66, vfork, int, (void))
X(SYS_munmap, 73, munmap, int, (void *, size_t), (void *)a0, (size_t)a1)
X(SYS_getpgrp, 81, getpgrp, int, (void))
X(SYS_setpgid, 82, setpgid, int, (pid_t, pid_t), (pid_t)a0, (pid_t)a1)
X(SYS_dup2, 90, dup2, int, (int, int), (int)a0, (int)a1)
X(SYS_fcntl, 92, fcntl, int, (int, int, ... void *), (int)a0, (int)a1, (... void *)a2)
X(SYS_fsync, 95, fsync, int, (int), (int)a0)
X(SYS_setpriority, 96, setpriority, int, (int, id_t, int), (int)a0, (id_t)a1, (int)a2)
X(SYS_socket, 97, socket, int, (int, int, int), (int)a0, (int)a1, (int)a2)
X(SYS_getdents, 99, getdents, int, (int, void *, size_t), (int)a0, (void *)a1, (size_t)a2)
X(SYS_getpriority, 100, getpriority, int, (int, id_t), (int)a0, (id_t)a1)
X(SYS_pipe2, 101, pipe2, int, (int *, int), (int *)a0, (int)a1)
X(SYS_dup3, 102, dup3, int, (int, int, int), (int)a0, (int)a1, (int)a2)
X(SYS_sigreturn, 103, sigreturn, int, (struct sigcontext *), (struct sigcontext *)a0)
X(SYS_listen, 106, listen, int, (int, int), (int)a0, (int)a1)
X(SYS_sigsuspend, 111, sigsuspend, int, (int), (int)a0)
X(SYS_thrkill, 119, thrkill, int, (pid_t, int, void *), (pid_t)a0, (int)a1, (void *)a2)
X(SYS_kill, 122, kill, int, (int, int), (int)a0, (int)a1)
X(SYS_fchown, 123, fchown, int, (int, uid_t, gid_t), (int)a0, (uid_t)a1, (gid_t)a2)
X(SYS_fchmod, 124, fchmod, int, (int, mode_t), (int)a0, (mode_t)a1)
X(SYS_setreuid, 126, setreuid, int, (uid_t, uid_t), (uid_t)a0, (uid_t)a1)
X(SYS_setregid, 127, setregid, int, (gid_t, gid_t), (gid_t)a0, (gid_t)a1)
X(SYS_rename, 128, rename, int, (const char *, const char *), (const char *)a0, (const char *)a1)
X(SYS_flock, 131, flock, int, (int, int), (int)a0, (int)a1)
X(SYS_mkfifo, 132, mkfifo, int, (const char *, mode_t), (const char *)a0, (mode_t)a1)
X(SYS_shutdown, 134, shutdown, int, (int, int), (int)a0, (int)a1)
X(SYS_mkdir, 136, mkdir, int, (const char *, mode_t), (const char *)a0, (mode_t)a1)
X(SYS_rmdir, 137, rmdir, int, (const char *), (const char *)a0)
X(SYS_getlogin_r, 141, getlogin_r, int, (char *, size_t), (char *)a0, (size_t)a1)
X(SYS_getthrname, 142, getthrname, int, (pid_t, char *, size_t), (pid_t)a0, (char *)a1, (size_t)a2)
X(SYS_setthrname, 143, setthrname, int, (pid_t, const char *), (pid_t)a0, (const char *)a1)
X(SYS_setsid, 147, setsid, int, (void))
X(SYS_ypconnect, 150, ypconnect, int, (int), (int)a0)
X(SYS_nfssvc, 155, nfssvc, int, (int, void *), (int)a0, (void *)a1)
X(SYS_mimmutable, 159, mimmutable, int, (void *, size_t), (void *)a0, (size_t)a1)
X(SYS_getfh, 161, getfh, int, (const char *, fhandle_t *), (const char *)a0, (fhandle_t *)a1)
X(SYS___tmpfd, 164, __tmpfd, int, (int), (int)a0)
X(SYS_sysarch, 165, sysarch, int, (int, void *), (int)a0, (void *)a1)
X(SYS_lseek, 166, lseek, off_t, (int, off_t, int), (int)a0, (off_t)a1, (int)a2)
X(SYS_truncate, 167, truncate, int, (const char *, off_t), (const char *)a0, (off_t)a1)
X(SYS_ftruncate, 168, ftruncate, int, (int, off_t), (int)a0, (off_t)a1)
X(SYS_setgid, 181, setgid, int, (gid_t), (gid_t)a0)
X(SYS_setegid, 182, setegid, int, (gid_t), (gid_t)a0)
X(SYS_seteuid, 183, seteuid, int, (uid_t), (uid_t)a0)
X(SYS_pathconf, 191, pathconf, long, (const char *, int), (const char *)a0, (int)a1)
X(SYS_fpathconf, 192, fpathconf, long, (int, int), (int)a0, (int)a1)
X(SYS_swapctl, 193, swapctl, int, (int, const void *, int), (int)a0, (const void *)a1, (int)a2)
X(SYS_mlock, 203, mlock, int, (const void *, size_t), (const void *)a0, (size_t)a1)
X(SYS_munlock, 204, munlock, int, (const void *, size_t), (const void *)a0, (size_t)a1)
X(SYS_getpgid, 207, getpgid, pid_t, (pid_t), (pid_t)a0)
X(SYS_semget, 221, semget, int, (key_t, int, int), (key_t)a0, (int)a1, (int)a2)
X(SYS_msgget, 225, msgget, int, (key_t, int), (key_t)a0, (int)a1)
X(SYS_shmdt, 230, shmdt, int, (const void *), (const void *)a0)
X(SYS_issetugid, 253, issetugid, int, (void))
X(SYS_lchown, 254, lchown, int, (const char *, uid_t, gid_t), (const char *)a0, (uid_t)a1, (gid_t)a2)
X(SYS_getsid, 255, getsid, pid_t, (pid_t), (pid_t)a0)
X(SYS_msync, 256, msync, int, (void *, size_t, int), (void *)a0, (size_t)a1, (int)a2)
X(SYS_pipe, 263, pipe, int, (int *), (int *)a0)
X(SYS_fhopen, 264, fhopen, int, (const fhandle_t *, int), (const fhandle_t *)a0, (int)a1)
X(SYS_kqueue, 269, kqueue, int, (void))
X(SYS_kqueue1, 270, kqueue1, int, (int), (int)a0)
X(SYS_mlockall, 271, mlockall, int, (int), (int)a0)
X(SYS_munlockall, 272, munlockall, int, (void))
X(SYS_closefrom, 287, closefrom, int, (int), (int)a0)
X(SYS_shmget, 289, shmget, int, (key_t, size_t, int), (key_t)a0, (size_t)a1, (int)a2)
X(SYS_sched_yield, 298, sched_yield, int, (void))
X(SYS_getthrid, 299, getthrid, pid_t, (void))
X(SYS___threxit, 302, __threxit, void, (pid_t *), (pid_t *)a0)
X(SYS___getcwd, 304, __getcwd, int, (char *, size_t), (char *)a0, (size_t)a1)
X(SYS_setrtable, 310, setrtable, int, (int), (int)a0)
X(SYS_getrtable, 311, getrtable, int, (void))
X(SYS___set_tcb, 329, __set_tcb, void, (void *), (void *)a0)
